### ISSUE TITLE
Power returns undef when it has multiple possible values.

### ISSUE THREAD

**Issue by jacobly0** [numworks/epsilon#102]
i^i computes as undef, presumably because it can have multiple values all of the form e^(2k&pi;-&pi;/2) for any integer k.  However, every calculator I've tested just uses e^(-&pi;/2), the value on the principal branch, which seems perfectly reasonable to me considering that &radic;(4) also has multiple possible values, -2 and 2, even though everyone expects it to return the principal value of 2.  I'd be happy to try to fix this, but I want to make sure I'm understanding the issue correctly first.

**Comment by artaxxx** [comment]
Thanks jacobly0! You're right, the calculator should display the result of e^(-π/2). We didn't do that because when we implemented complex calculations we chose not to define a complex logarithm. And we saw i^i as exp(i*ln(i)). That's definitely something to reconsider and use Euler's formula instead.
