### ISSUE TITLE
Update the Android app from 10.0.1 to 11.2.0

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1038]
#### Problem you'd like to fix
The current version of Epsilon in the Android app is 10.0.1

#### Describe the solution you'd like
Update the app to have the latest 11.2.0 version – as in the online simulator

#### Describe alternatives you've considered
Going the the online simulator on the phone works – but not offline

#### Additional context
Maybe the ios app needs an update, too?
As a mean of communication, showing the app has updated on every pupil’s phone already using it, during the summer holidays, is a big upside, isn’t it?

**Comment by RemyDCF** [comment]
It seems this issue was fixed 🙂
![Screenshot_20190702_205317_com android vending](https://user-images.githubusercontent.com/11600393/60538788-8d293580-9d0b-11e9-892d-91bd2f57fb7c.jpg)
![Screenshot_20190702_205433_com numworks calculator](https://user-images.githubusercontent.com/11600393/60538814-9d411500-9d0b-11e9-9077-e8fbc6517e7d.jpg)

**Comment by 0b101** [comment]
> Maybe the ios app needs an update, too?

Yes, the iOS app still appears to be out of date.

**Comment by LudovicRousseau** [comment]
The current iOS version is 10.0.5.
It is also outdated.

**Comment by Ecco** [comment]
Version 12.2.0 is now online on all stores.
