### ISSUE TITLE
Improve the automatic zoom

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1058]
#### Problem you'd like to fix

1. Open the Functions app
2. Type in `f(x)=exp(x)` and `g(x)=ln(x)`
3. Plot
4. Notice how the default zoom is sub-optimal

#### Screenshots

The resulting zoom is decent for `exp`, but clearly doesn't show much about `ln`.

![screenshot (4)](https://user-images.githubusercontent.com/55989/63938768-dd9be580-ca65-11e9-9add-7311fe278d03.png)

#### Describe the solution you'd like

In this case, having Y between -8 and 8 would give a much better result.

![screenshot (5)](https://user-images.githubusercontent.com/55989/63938807-fdcba480-ca65-11e9-802f-11d4c99765b3.png)

**Comment by suazhero** [comment]
Too bad is not been integrated in 12.2.0. Hopefully in the next version. Genrally speaking, Y scale is always way too wide.
Thx

**Comment by suazhero** [comment]
Hi there, is anyone working on this? Latest versions are pretty good! But it remains the most anoying behavior on this calculator :( Thx

**Comment by suazhero** [comment]
Hello @Ecco @LeaNumworks @EmilieNumworks 

Is this dev active?
Today, the Y scale is computed according to the X scale, such as Ymin and Ymax are chosen according to f(Xmin) or f(Xmax). 
I assume the reason for that is we want to have a drawing for the whole X scale.

This gives a Y scale that may result in ploting irrelevant points, and hiding what's really significant.

With exp(x) for instance, the auto axes gives the following:
![image](https://user-images.githubusercontent.com/55035114/74819220-59356b80-5300-11ea-9a75-11b5105f014b.png)

which shows how fast it grows, but hides completely significant behaviour in [-4;4].
Obvisouly the solution could be to reduce the X scale to [-4;4],  which gives a more significan result.
![image](https://user-images.githubusercontent.com/55035114/74819953-79195f00-5301-11ea-93a3-ce390a72881f.png)

Playing with Y scale, the workaround proposed in the first place, gives the best result in my opinion, but we have to accept not having something drawn for the whole X scale.
![image](https://user-images.githubusercontent.com/55035114/74820074-abc35780-5301-11ea-92db-74d74eb2f47e.png)

So i believe the engine should be improved to focus on what's really significant, instead of wanting to have something plotted for every X in the range defined.

As an example, here's the way a Casio graph 85 SD will plot exp(x) (auto zoom)
![image](https://user-images.githubusercontent.com/55035114/74820366-2c825380-5302-11ea-8f58-af5315d5aed7.png)

And taking the example of exp(x) and ln(x), here's what would be plotted
![image](https://user-images.githubusercontent.com/55035114/74820656-b16d6d00-5302-11ea-977c-87703497a585.png)

Again, in my opinion, that's much more clear and represent only significant values

**Comment by suazhero** [comment]
Hello team @LeaNumworks @EmilieNumworks @Ecco :)
Any new about this one? User experience is really affected when using the function app on a daily basis.
If not improved immediately, a workaround could be to allow the user to have his own predefined zoom setting, and make it persistent.
Currently, the zoom has to be reset any time a new function is plot since auto zoom is always enabled.
For instance Xrange = [-10;10] and Yrange=[-10;10] works much better in 99% of the case than auto zoom. If you could add an option to enable or not auto zoom and/or keep the user choice in memory it would be perfect.

**Comment by artaxxx** [comment]
Hi @suazhero , this topic has not been forgotten, we will be working on it soon!

**Comment by artaxxx** [comment]
This problem is solved in 15.0.0
