### ISSUE TITLE
implicit multiplication

### ISSUE THREAD

**Issue by ranousse** [numworks/epsilon#1071]
In the function menu`(x+3)(x+2)` works fine, `2x(x+5)` works fine too, `x(x+3)` does not (we have to add the x sign between `x` and `(x+3)`).

I the later case, I think the calculator sees the expression as function `x` applied to number `x+3`.
It seems a little awkward to me. Was it intended?

**Comment by Ecco** [comment]
It is indeed by design, and your explanation is spot on.

Is there any alternative you would like better?

**Comment by ranousse** [comment]
For an experienced user it's not a problem and it's rather better than other calculators that don't allow things such as 3x+2 -> f(x)

For a pupil, it seems much more annoying.

Maybe it would be possible to interpret x(x+3) as as a function of x+3 only if the function x is defined somewhere else (which is not very likely).
Moreover, in the function menu, x being the variable maybe one could prevent it to be interpreted as a function in some cases.

**Comment by suazhero** [comment]
Hi. Raised more or less the same some time ago (with xln(x) where xln is considered as a function even if it doesn't exist anywhere else) and here's the feedback : https://www.numworks.com/fr/blog/partager-fonctions-dans-toutes-les-applications/
French, but clearly states the choice

**Comment by Ecco** [comment]
> Maybe it would be possible to interpret x(x+3) as as a function of x+3 only if the function x is defined somewhere else (which is not very likely).

It may sound like a good idea but I'd be very reluctant to doing things this way. I would really like to avoid making the expression parser context-dependant.

> xln(x) where xln is considered a function

That's even tougher to address because here the parser is not even involved. `xln` and `ln` are just different tokens.

**Comment by suazhero** [comment]
Thx. Yeah well to conclude we all agree it's the best implementation in both cases. But not the most intuitive to high school students who may elide x sign. Especially since it sometimes works. Maybe to keep the best out of it, making the x sign mandatory everywhere would avoid any confusion

**Comment by RubenNumworks** [comment]
Since version 13, an expression of the form `a(b)` is parsed according to the context:
- if `a` refers to a function's identifier, `a(b)` is `a` evaluated at `b`
- otherwise, `a(b)` is the product of `a` and `b`.

<img width="202" alt="Capture d’écran 2020-03-09 à 12 20 02" src="https://user-images.githubusercontent.com/45850449/76208741-8dfe5980-6200-11ea-915f-cdbebbaec840.png"> <img width="202" alt="Capture d’écran 2020-03-09 à 12 20 34" src="https://user-images.githubusercontent.com/45850449/76208742-8e96f000-6200-11ea-97a8-98acc0c68e13.png"> <img width="202" alt="Capture d’écran 2020-03-09 à 12 21 06" src="https://user-images.githubusercontent.com/45850449/76208744-8f2f8680-6200-11ea-8530-e330be6cd4b8.png">
