### ISSUE TITLE
-8 in power of 1/3 should be  undefined.

### ISSUE THREAD

**Issue by alexeyneu** [numworks/epsilon#1080]
So you should change it to cubic root of -8 on screen .

**Comment by Ecco** [comment]
I'm not sure what you mean. `(-8)^(1/3)` gives `-2`. Is anything wrong with that?

**Comment by alexeyneu** [comment]
yeah coz a^x  defined only for a>0 (i do not remember about a=0)  for not natural x.

**Comment by Ecco** [comment]
I guess it all boils down to the definition you decide to use for `a^x`.

**Comment by alexeyneu** [comment]
a^x if written exactly like this is pseudocode for a<sup>x</sup>  which is math function you cant redefine

**Comment by alexeyneu** [comment]
![Безымянный](https://user-images.githubusercontent.com/31589671/65813706-937f5e80-e1e1-11e9-90b5-188d5c62c037.png)  
as it should be

**Comment by Will-of-R-Learn** [comment]
Well if you look at this basic identity, then
![image](https://user-images.githubusercontent.com/29755107/65905322-fc332a80-e3dd-11e9-91f7-911f4ab3a77f.png)

(-8)<sup>(1/3)</sup>=<sup>-3</sup>√-8=-2
So they should be equal

and google agrees
![image](https://user-images.githubusercontent.com/29755107/65905794-df4b2700-e3de-11e9-8eb2-21fd37be47fd.png)

Whatever calc you are using is the one with the problem I think

**Comment by alexeyneu** [comment]
that picture you'd posted is for kids  
hp first sci calc released when google staff starts their lives at best.  It's screencopy of hp prime  
when i start this issue i didnt test it there. It's from math lessons in our school

**Comment by suazhero** [comment]
@alexeyneu is right pointing out the righting is abusive, since a^x is indeed undefined when x is rational and a < 0. It's really a matter of definition. But does the numworks calculator have a nth root symbol at all?

**Comment by alexeyneu** [comment]
yeah it has. I've thinking it has just ![](https://latex.codecogs.com/gif.latex?\sqrt[n]{x}) button but i see it hasn't got it. But you can use ![](https://latex.codecogs.com/gif.latex?\sqrt{..}) and then left arrow and type n there.

**Comment by suazhero** [comment]
Which version? Don't have that using version 11.2.

**Comment by adriweb** [comment]
Manually, not from the physical button: choose the root function in the toolbox. Then you can go to the left and enter a number.

**Comment by suazhero** [comment]
Oh wow thx

**Comment by alexeyneu** [comment]
i've pressed button in online simulator. Without toolbox or so.
![Безымянны3й](https://user-images.githubusercontent.com/31589671/65952102-0a1e9500-e44a-11e9-8027-80fe9988595f.png)

**Comment by adriweb** [comment]
Yes, the button is only a shortcut to square root template and not to the n-th root template.

**Comment by alexeyneu** [comment]
but i didnt have to select anything in toolbox(?)

**Comment by alexeyneu** [comment]
haha Just test it .it doesn't work.

**Comment by adriweb** [comment]
It works as per what Romain said, that is. 

![Image](https://i.imgur.com/6vh3adk.jpg)

Note that I'm testing with the iOS app which isn't updated to the latest epsilon version yet, as I don't have the calc with me right now. 

Anyway, it's up to the NumWorks team to decide what to do or not do now I guess.

**Comment by alexeyneu** [comment]
no i mean stuff with square root button. It allows you to type  `n` but cant solve it

**Comment by suazhero** [comment]
Well it would be convenient for the hw button to return root(x,n) and allow to leave the exponent blank when actually wanting square root. 
Back to the initial topic, is the suggestion that the calculator returns ³✓-8 when the input is (-8)^(1/3) ?

**Comment by alexeyneu** [comment]
@suazhero yeah. And i've seen it done that sometimes

**Comment by alexeyneu** [comment]
![](https://latex.codecogs.com/gif.latex?\left(-8\right)^{\frac{1}{3}}) fails to fit any domain known in real math.  
There're two for this : a<sup>n</sup>   ![](https://latex.codecogs.com/gif.latex?a\,\in\,\mathbb{R})   ,  ![](https://latex.codecogs.com/gif.latex?n\,\in\,\mathbb{Z})   
and   
a<sup>x</sup>  ![](https://latex.codecogs.com/gif.latex?a\geq0) , ![](https://latex.codecogs.com/gif.latex?x\,\in\,\mathbb{R})

**Comment by fbeleznay** [comment]
(-8)^(1/3) is indeed not usually defined among real numbers, but I do not think it is a mistake doing it. Exponentiation can be extended to complex numbers, when (-8)^1/3 is meaningful. However this complex exponentiation is problematic (either not continuous or multivalued). The wikipedia article on exponentiation can be a good starting point to read about it ( https://en.wikipedia.org/wiki/Exponentiation ).
Alexeyneu mentioned the HP prime. If you turn on complex calculations and  try (-8)^1/3, you still get an error message. However, if you try (-8+0*i)^1/3 (which is the same number in the base) you do get an answer (which is not -2). The reason it is not -2 is that there are three complex numbers with the property that z^3=-8 (one of which is -2, the other is what the HP prime gives and there is a third one). All three can be meaningfully considered to be (-8)^1/3 (and in some cases all three together are called (-8)^1/3). The choice made by HP prime is somewhat arbitrary (although well-defined).
If you turn on complex calculations in Numworks (in settings) and try (-8)^1/3, you will not get -2. You get the same answer as the one the HP prime gives. As I said, there are three numbers as a candidate for being (-8)^1/3. One real and two complex. In real mode the HP prime gives an error message, the Numworks gives the real value. In complex mode they both give the same complex number.
I did not find anything about this in the user manual of either the HP prime or Numworks though.

**Comment by nsajko** [comment]
![screenshot](https://user-images.githubusercontent.com/4944410/67128842-6e807900-f1ec-11e9-949b-fd7c6c584f6d.png)

Interestingly, another possible solution is chosen with a non-"Real" setting for the "Complex format" option in Settings.

I guess the "Real" "Complex format" setting searches for a real solution?

**Comment by fbeleznay** [comment]
I think in complex mode Numworks is using the algorithm described in the [Wolfram Mathematica documentation of the power function](https://reference.wolfram.com/language/ref/Power.html).

x^y=e^(y*Log(x)), where Log(x) is the complex logarithm function.
So now the question is, what is Log(x)? For complex numbers, it is Log(|x|)+i*Arg(x) (where Log(|x|) is the usual real natural logarithm).
Since the argument of x is not unique, Wolfram Mathematica (and based on this example, Numworks) chooses the principal argument between -pi and pi (not including -pi, including pi).

If I translate this general approach to the case of (-8)^1/3, we get the following:
(-8)^1/3=e^(1/3*Log(-8))
Log(-8)=Log(8)+i*Arg(-8)
The principal argument of -8 is pi, so Log(-8)=Log(8)+i*pi
Using this, e^(1/3*Log(-8))=e^(1/3*(Log(8)+i*pi))=e^(1/3*Log(8))* e^(i*pi/3)
Since 1/3Log(8)=1/3*Log(2^3)=Log(2), we get e^(1/3*Log(8))=e^Log(2)=2 (note, that I am using Log for the natural logarithm)
Hence (-8)^1/3=2*e^(i*pi/3), as given by Numworks.

Interestingly, Numworks gives the exact value for (-8)^1/3 (as seen in the previous message), but it does not give the exact value of ln(-8) as ln(8)+i*pi. Maybe this can be changed in the future?

**Comment by nsajko** [comment]
@fbeleznay Maybe you should open another bug-report for displaying ln(-8) as ln(8) + i*pi?

**Comment by alexeyneu** [comment]
@fbeleznay you can try to define third `f(x)` there but you sould not consider that it is defined

**Comment by fbeleznay** [comment]
@alexeyneu I am not sure I understand your comment. The concept of multivalued complex exponential is an established mathematical concept to extend the definition of exponentiation to cases where the real function does not work (for example to negative base). It is not me who want to do this, it is done by others and accepted by the mathematics community. You can read a quite detailed version of this for example in http://scipp.ucsc.edu/~haber/ph116A/clog_11.pdf

**Comment by alexeyneu** [comment]
it's about 
> but I do not think it is a mistake doing it

**Comment by nsajko** [comment]
@alexeyneu Dude. Why would you rather your calculator give you no answer than give you one? It is simply a matter of usefulness, `undefined` is not useful, while giving one answer, among `n` correct answers, *is* useful.

**Comment by nsajko** [comment]
Note that even purely on the reals, x^(1/2) is multivalued.

**Comment by alexeyneu** [comment]
1. coz say you may have this question on exams  
  
2. x<sup>1/2</sup> really is f(x)=x<sup>1/2</sup> with its domain. And it's not multivalued

**Comment by AlexPMLikesNumWorks** [comment]
As a guy who studied mathematics and physics, (-8)^1/3 is definitely 2e^pi/3. Generally speaking, thinking in the complex plane usually makes more sense. If complex arithmetics are forbidden, then (-8)^1/3 must be rejected.

Note that the semantics of the n-th root are slightly different than the 1/n-th power, depending on your acceptance of complex numbers or not. For example, it is widely accepted that the 3rd-root of 1 is e^(2pi/3), generator of the multiplicative group of the 3-roots of the unit (also known as j), whereas 1^(1/3) would not be understood other than being 1.

**Comment by alexeyneu** [comment]
looks like nobody wanna talk in function/domain terms. Different math school idk.

**Comment by suazhero** [comment]
Well, doesn't look that simple.

The asumption is that a^x is only defined for a > 0 when x is non integer.

But you can find in this post that the definition can be extended to a < 0. https://math.stackexchange.com/questions/1628759/what-are-the-laws-of-rational-exponents

And your example is taken by someone who ends up with the following comment:

"Reading the paper by Tirosh and Even, I was surprised to learn this matter has drawn serious attention from math educators.

A long time ago, I assumed that, apart from complex extensions, a^x for non-integer x should be defined only for a>0. I reasoned that it made no sense to have a function (−2)^x defined only for rational numbers x with odd denominator. I objected strenuously to notations like (−8)^1/3.

But that was before I taught a calculus class, which is when I realized why some textbook authors are so happy to define ax for a<0, following the second convention. The reason is that the formula d/dx(x^r)=rx^(r−1) is perfectly valid for x<0 and r with odd denominator."

**Comment by alexeyneu** [comment]
But thats not end . He write the rest in comments. Haha  
conclusion is that you need to reddefine what a<sup>x</sup> is.

**Comment by artaxxx** [comment]
Let's close this issue since we keep this definition in real mode.
