### ISSUE TITLE
NumWorks reset by entering a formula

### ISSUE THREAD

**Issue by nhyBinary** [numworks/epsilon#1165]
Hey! I've found a quite funny bug (or maybe it's not, but I loved it). This bug allow you to simply reset the NumWorks with a formula.

Go in Functions > Add function > write "sin(x+46²)", then click "Plot graph", and the NumWorks will reset.

Here a video of the bug : https://www.youtube.com/watch?v=PJNMMJbnsqI

Version: Lastest on NumWorks website, v11.2.0 ( 07a9e90 )
Also works with 10.1.0 ( 48c088e )

**Comment by Ecco** [comment]
Appears to be fixed in 12.1.0-beta (a8cea1f)

**Comment by Ecco** [comment]
Doesn't crash on master (2ff0b789f) either. Note that the rendering is different on master as compared to 12.1.0 beta.

**Comment by EmilieNumworks** [comment]
The crash was due to an out-of-bound memory access: the periodicity of the function was miscomputed to 'inf', the plot range was set to [-inf, inf] which would lead to draw an infinite number of labels, thereby it looked for a buffer out of bounds. The version 12.1.0 forbids to set an infinite bound to the plot range by capping it. This prevents from crashing but does not fix the wrong periodicity.
The PR #1167 fixes:
- the periodicity computation
- it adds an assertion on the number of labels.
