### ISSUE TITLE
Can't compile epsilon

### ISSUE THREAD

**Issue by EliteAsian123** [numworks/epsilon#1233]
Hello. Sorry that this issue isn't really about Epsilon, but I can't figure it out! The issue is is that `pkg-config` seems to be missing. I looked at #549 but `pacman -S mingw-w64-x86_64-pkg-config` says that `pkg-config` is up to date, but when I try to run the makefile it doesn't work.

Here is a screenshot of the error:
![image](https://user-images.githubusercontent.com/29520859/70279565-be0f0a00-1784-11ea-8ac8-2b5c055671b6.png)

Thanks!

**Comment by Ecco** [comment]
It also says that you don't have gcc. I don't know what your issue is, but I think something's wrong with your MSYS2 install. Anyway, our CI pipeline manages to build on Windows, so I don't think it's a bug in Epsilon's code or instructions.

For the record, here's the command that runs on the CI workflow: `pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-freetype mingw-w64-x86_64-pkg-config make mingw-w64-x86_64-python3 mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-libpng`

**Comment by Nawor3565** [comment]
This issue should be re-opened. Following the [official compiling instructions for Windows](https://www.numworks.com/resources/engineering/software/build/) no longer works, but it's easy to fix:

`pacman -S pkg-config

echo "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:mingw64/lib/pkgconfig" >> .bashrc
`
