### ISSUE TITLE
Turtle and Kandinsky modules affect each other undesirably

### ISSUE THREAD

**Issue by Flirno** [numworks/epsilon#1248]
When calling the module turtle and kandinsky the order you are calling them matters.
If you call the turtle module before the kandinsky module **the color function for turtle will not work**.

For example with this script :
![screenshot (7)](https://user-images.githubusercontent.com/34623058/70846777-1cab4680-1e5d-11ea-9348-028f90d7b31c.png)

you get that : 
![screenshot (8)](https://user-images.githubusercontent.com/34623058/70846798-70b62b00-1e5d-11ea-8608-89585a860f0f.png)

With the same script but this time we call the turtle module before the kandinsky module : 
![screenshot (9)](https://user-images.githubusercontent.com/34623058/70846799-71e75800-1e5d-11ea-8053-5cd3f7e6035e.png)

you get that :
![screenshot (10)](https://user-images.githubusercontent.com/34623058/70846800-73188500-1e5d-11ea-8008-76cad73b5a42.png)

Still effective in the latest version of epsilon 12.4.0

**Comment by Ecco** [comment]
Sorry, but that's not an Epsilon bug: the error is in your Python code 😛 

Indeed, the "color" function is defined both in Kandinsky and in Turtle. So depending on which module you import first, writing "color" will either be expanded to `Kandinsky.color` or `Turtle.color`.

The fix is to `import turtle` and then `turtle.color` 😄
