### ISSUE TITLE
Euclidian division

### ISSUE THREAD

**Issue by yeKcim** [numworks/epsilon#129]
In Calculation: Add an easy way to display euclid's division like
```
eucl(157,13)
        q=12 r=1  
```
I haven't find another solution than two operations : `quo(157,13)` and `rem(157,13)` 

Enhancement
Software version: 1.1.2

**Comment by ian-abbott** [comment]
But what would the 'ans' variable contain after this?

**Comment by yeKcim** [comment]
@ian-abbott: 12,076923077 should be a solution

**Comment by adriweb** [comment]
Supporting a list type would solve this. For instance, it would return `{12, 1}`, so `ans` could contain that.
(the command would be an alias for `{quo(157,13),rem(157,13)}`

@yeKcim not really: there needs to be programmatic access to any result, it can't just be something displayed on screen at some point and not accessible anymore!

**Comment by yeKcim** [comment]
For information, Casio FX-92 college displays "Q=12; R=1" and Ans is equal to Q.

**Comment by EmilieNumworks** [comment]
Since version 13.0.0, if you input '157/13', you'll have the Euclidian division in the additional results displayed in a pop-up.

<img width="215" alt="Capture d’écran 2020-03-06 à 13 57 33" src="https://user-images.githubusercontent.com/31415152/76085510-7b8ee080-5fb2-11ea-8198-8a96c353b435.png">

<img width="213" alt="Capture d’écran 2020-03-06 à 13 57 45" src="https://user-images.githubusercontent.com/31415152/76085507-7af64a00-5fb2-11ea-9755-47354362e403.png">
