### ISSUE TITLE
Integrating the bell curve returns "undef"

### ISSUE THREAD

**Issue by madhatter0** [numworks/epsilon#130]
int(e^(-(x^2)),-5,5) returns undef

I'm pretty sure the normal distribution function is well-defined throughout this range.  Doing the integral from -5 to 0, and from 0 to 5, are both successful, as is doing it from -1 to 1.  I'm happy to be shot down, but I think the function ought to be well-defined and thus the integral calculable.

Software version is 1.1.2, built under Fedora 26.

**Comment by Ecco** [comment]
You are correct, this is indeed a bug. The result should be around `1.7724`.

**Comment by ian-abbott** [comment]
In "poincare/src/integal.c" `Integral::templatedEvaluate`, the 4th parameter of the call to `adaptiveQuadrature<T>` should be changed from `k_maxNumberOfIterations` to `0` or `1` (not sure which). (Or alternatively, `Integral::AdaptiveQuadrature` could be changed to decrement `numberOfIterations` at each recursion step instead of incrementing it.) As it currently stands, the code only does one step, and if the error is too high, it returns `NAN` (which is converted to "undef").

**Comment by ian-abbott** [comment]
[My fix](../pull/140)

**Comment by artaxxx** [comment]
Thanks @ian-abbott !
