### ISSUE TITLE
Simulator might skip too many redraws

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1300]
#### Describe the bug
When you change of workspace in i3, the simulator isn't diplayed until you change the tab system or you click on the window.

#### Screenshots
https://youtu.be/JrtV3G-b2jA

#### To Reproduce
1. Start the simulator on i3
2. Change workspace
3. Come back to the workspace with the simulator

#### Expected behavior
I expected the window to be showed

#### Environment
 - Epsilon master (7123c7c)
 - Linux simulator with i3

**Comment by boricj** [comment]
Check if you can reproduce this with a standalone hello world SDL program. I would assume this is a SDL bug rather than an epsilon-specific bug.

**Comment by Ecco** [comment]
Yes, I can hardly see how this could be Epsilon-related 😄 Closing for now.

**Comment by jacobly0** [comment]
This is certainly epsilon's fault, given that commenting out [these lines](https://github.com/numworks/epsilon/blob/master/ion/src/simulator/shared/main_sdl.cpp#L126-L128) fixes it.  What happens is that you only track the dirty flag for when something in *your* program changes, and ignore redraws caused by external factors, like the window being moved around.  In fact, you might even be able to reproduce this on other window managers/oses by dragging the window partially off screen or partially obscuring it with another window and watching the obscured part not get redrawn.  In fact, there is an SDL event for this, see [SDL_WINDOWEVENT_EXPOSED](http://wiki.libsdl.org/SDL_WindowEventID#line-13).

**Comment by Ecco** [comment]
Oh, you're 100% right, my mistake. Thanks @jacobly0 !

**Comment by RedGl0w** [comment]
Note : this also appears on Kde Plasma (one of the most used display manager).

**Comment by RedGl0w** [comment]
> This is certainly epsilon's fault, given that commenting out [these lines](https://github.com/numworks/epsilon/blob/master/ion/src/simulator/shared/main_sdl.cpp#L126-L128) fixes it. What happens is that you only track the dirty flag for when something in _your_ program changes, and ignore redraws caused by external factors, like the window being moved around. In fact, you might even be able to reproduce this on other window managers/oses by dragging the window partially off screen or partially obscuring it with another window and watching the obscured part not get redrawn. In fact, there is an SDL event for this, see [SDL_WINDOWEVENT_EXPOSED](http://wiki.libsdl.org/SDL_WindowEventID#line-13).

I don't understand what's the goal of :
```cpp
sNeedsRefresh
```

**Comment by RedGl0w** [comment]
Seems to be well fixed by #1602 .
