### ISSUE TITLE
Add degrees Celsius and Fahrenheit in "Temperature"

### ISSUE THREAD

**Issue by A2drien** [numworks/epsilon#1308]
#### Problem you'd like to fix
There are only kelvins in "Temperature", which is rather useless (but it's already good ^^).

#### Describe the solution you'd like
I propose to add the degrees Celsius and Fahrenheit, which will allow easy conversions if necessary.

#### Describe alternatives you've considered
_C and _F are already taken by Coulomb and Farad.
I therefore propose to add _Ce and _Far, or _°C and _°F for these additions.
If the "°" is difficult to put in the toolbox, I suggest adding it when doing Alpha + Ans or Alpha + ×10^x (and add the gray symbol for N0120 or N0200 ^^).

**Comment by RubenNumworks** [comment]
Thank you for your suggestion. The set of possible units indeed needs to be completed. Celsius was not added yet because it requires a very specific treatment.

(a) For example, what should be the result of `20°C + 30°C` ? At first sight, a natural (somehow naive) answer would be `50°C`. However, after converting each term of the addition into Kelvins, the result should be `((20+273.15) + (30+273.15)) K = 596.3 K = 323°C` which is very different. _Should addition of temperatures in degrees Celsius be forbidden at all ?_ 

(b) On the other hand, what should be the result of `1 mole × 20°C` ? As above, it may be `20 mole×°C`. Or after converting into Kelvins, `1 mole × (20 + 273.15) K`. Or even `20 mole × 274.15 K` which is strange but valid when considering that `1°C = 274.15 K`. _Degrees Celsius should most certainly be forbidden in products. Temperature in physical formulas as `PV=nRT` are always expressed in Kelvins. Degrees Celsius are only convenient for expressing temperature in an every-day-life scale (in some countries or regions)._

Probably that
- no conversion between `K`and `°C`should be authorized in any intermediate computation.
- any `[value] °C`  should be immediately converted into Kelvins before performing any other operation
- `°C` should be forbidden inside a product of units
- `°C` might appear only in expressions of the form `[value] °C` and nowhere else.

Those considerations
- are quite independent from Epsilon and may actually rise whenever dealing with temperature,
- should be clarified before adding `°C` in Epsilon.

Any feedback is of course welcome.

The same goes for degrees Fahrenheit.

**Comment by adriweb** [comment]
Some interesting discussion about this here: https://physics.stackexchange.com/questions/132720/how-do-you-add-temperatures

**Comment by artaxxx** [comment]
Fixed in 15.0.0
