### ISSUE TITLE
Inaccurate trigonometric regression

### ISSUE THREAD

**Issue by Will-of-R-Learn** [numworks/epsilon#1319]
#### Describe the bug
The trigonometric regression algorithm has a bug in it, which causes inaccurate regression.

#### Screenshots

![screenshot](https://user-images.githubusercontent.com/29755107/74831183-ba7a3080-533a-11ea-8324-e81a986630b6.png)

#### To Reproduce
The following data causes this issue:
![screenshot (2)](https://user-images.githubusercontent.com/29755107/74831227-d2ea4b00-533a-11ea-866c-bb73ac03b835.png)
![screenshot (3)](https://user-images.githubusercontent.com/29755107/74831228-d41b7800-533a-11ea-909c-a55a22bc0991.png)

#### Expected behavior
Should be a clear mapping of the points which lie in a curve.

#### Environment
 - Epsilon version: 12.4
 - N100

**Comment by LeaNumworks** [comment]
Hi @Will-of-R-Learn, thank you for this issue, and thanks for the screenshots!
I believe the problem was solved by a233b0262, the example you gave works properly on master and on the latest epsilon version (13.0.0).

![Screenshot 2020-02-19 at 13 54 47](https://user-images.githubusercontent.com/32390188/74836392-98bf8000-531f-11ea-8f09-5d1a55d41126.png)

I am thus closing the issue.
