### ISSUE TITLE
Add a new backgroud and text color argument with Kandinsky draw_string

### ISSUE THREAD

**Issue by le-grand-mannitout** [numworks/epsilon#1325]
Hi Numworks team ! I often would like to set a different color to the text or to the background, with the function "draw_string()".

The Kandinsky draw_string function is verry nice, but it could be well better by adding these 2 news arguments : this is currently quite difficult to do a nice graphic interface, without this functionality..

Here is a potential syntax of the function with this modification :
`draw_string("text", x, y, color_text, color_background)`

Thanking you in advance,

**Comment by RedGl0w** [comment]
https://github.com/numworks/epsilon/blob/80c03220dd10ddf1d2bdadc55b240b8a4dc03c5e/python/port/mod/kandinsky/modkandinsky.cpp#L71
This already exists
It's just not in the toolbox
I advise you to rename your issue to `Add the colorbackground parameter in the toolbox of drawstring in kandinsky python module` or smth like this...

**Comment by LeaNumworks** [comment]
Hello @le-grand-mannitout,
Thanks for creating this issue!
As @RedGl0w said, you can already use the `draw_string` method with those additional arguments, just like you suggested: `draw_string("text", x, y, color_text, color_background)`
We decided not to mention these arguments in the toolbox though, because a clear explanation would not fit in the toolbox space.
