### ISSUE TITLE
x(n) 

### ISSUE THREAD

**Issue by JuniorDelaure** [numworks/epsilon#1388]
The result of x(5) or any other calculation with x( is undef

**Comment by RubenNumworks** [comment]
Did you defined `x` before?

**Comment by JuniorDelaure** [comment]
x is defined. Also plotting a function with x() isn't possible

**Comment by RubenNumworks** [comment]
Up to version 12, an expression of the form `a(b)` used to be parsed as _the function `a` evaluated at `b`_. In particular, if you define `x` as a variable and not as a function, then `x(5)` results in `undef`. See #1071 for a similar discussion.

The behavior has changed since version 13. See https://github.com/numworks/epsilon/issues/1071#issuecomment-596473007.
