### ISSUE TITLE
Degrees not implemented on complex?

### ISSUE THREAD

**Issue by AndreasET** [numworks/epsilon#1397]
#### Describe the bug
Calculation of complex numbers ignores 'angle measure' setting,
input and output of degrees is handled as radians.

#### Screenshots
![screenshot (3)](https://user-images.githubusercontent.com/39586213/76451136-411cad80-63cf-11ea-98a9-ca8066f77d47.png)
![screenshot (4)](https://user-images.githubusercontent.com/39586213/76451154-4843bb80-63cf-11ea-9b50-a519005dfa1e.png)
![screenshot (5)](https://user-images.githubusercontent.com/39586213/76451171-4ed23300-63cf-11ea-9ca8-b5bc67c387c2.png)

#### To Reproduce
1. Enable complex mode (i.e. cartesian)

#### Expected behavior
Handle degrees as expected.
Screenshot 1 equals to  ' cos(45°) + i*sin(45°) ', 
the correct result is shown in screenshot 2.
Screenshot 3 shows the radian result, but degrees is expected.

#### Environment
- Epsilon 13.0.0
- Simulator

**Comment by RubenNumworks** [comment]
Isn't accepting (or choosing between) degrees or radians a question of usage?
For instance, the common trigonometric functions (sin, cos, tan) usually accept both degrees and radians (or even gradians), provided that the unit is specified in the context or by the settings.
On the other hand, it seems that the complex exponential and logarithm functions do not generally accepts angles in degrees. Any feedback about that is welcome.
Related to https://github.com/numworks/epsilon/issues/1161#issuecomment-545358250

Since the arg and log functions are closely related, it seems natural that the former follows the same conventions as the latter. However this choice may lead to some odd results:
![screenshot](https://user-images.githubusercontent.com/45850449/76517586-d8304680-645d-11ea-96e5-a83e92dbaca4.png)

**Comment by matheod** [comment]
>  it seems that the complex exponential and logarithm functions do not generally accepts angles in degrees

I agree

**Comment by artaxxx** [comment]
I agree too. I don't think the firmware should handle arguments in degrees so I'm closing this issue.
