### ISSUE TITLE
sin(1E50) = sin(1E50 + pi/2) = 0

### ISSUE THREAD

**Issue by mjfcolas** [numworks/epsilon#14]
In the simulator, it seems that the sinus of a big number is always 0.

**Comment by jacobly0** [comment]
It is not very meaningful to try to compute periodic functions with floating point values (the kind that both calculators and computers use) where the exponent is near or larger than its own precision.  So if you are computing with 10 digits, sin(10<sup>10</sup>) is fairly meaningless considering that 10<sup>10</sup>+&pi; rounds to exactly 10<sup>10</sup>.  I think the best solution to this problem is to throw a domain error for arguments  too large in magnitude to be meaningful.  As an example, another calculator that computes with 14 decimal digits of precision errors when the argument of sin/cos/tan is &ge;10<sup>12</sup>.

**Comment by artaxxx** [comment]
This is fixed in the last version 1.2.0
