### ISSUE TITLE
Add "smart" mode for degrees

### ISSUE THREAD

**Issue by Zezombye** [numworks/epsilon#147]
For degree mode, a thing that would be nice to have is "smart mode", which automatically chooses between radians and degrees.
If the argument involves pi (pi/2, pi/4, pi, 2pi...) it chooses radians, else it chooses degrees. I don't think there is a risk of getting an unwanted result, since you wouldn't calculate sin(pi) in degrees, or sin(90) in radians.
For functions such as asin, acos, atan, the result would be based on the current setting. So in the settings, you could choose between radians and degrees, and check "smart mode".

**Comment by boricj** [comment]
This would break down very quickly without an exact calculation engine. It would interact poorly with gradians. I'm also not convinced this is a good idea since the angle mode would not be explicit, which would be even worse if the inverse trigonometric functions do not follow the same logic as the normal ones.

**Comment by Ecco** [comment]
It's always very tempting to do things magically for the end user — as long as the magic is reliable. I would agree with @boricj : while this sounds like a great idea, I think there are cases where it could end up worse than the baseline scenario (e.g. can we be postive `cos(1)` means `cos(1degree)`?).

That being said, maybe you're trying to solve a deeper issue? From our experience, students initially learn about degrees (easier because they don't involve pi), and then switch to radians entirely. So it makes sense to have a device-wise angle setting.

**Comment by Ecco** [comment]
We're closing this issue. Don't hesitate to re-open if you have an idea of a reliable heuristic we could use.
