### ISSUE TITLE
Square root of a unit returns undef

### ISSUE THREAD

**Issue by Moddingear** [numworks/epsilon#1565]
#### Describe the bug
n-th root of any unit to the k*n-th power returns undef, causing the entire calculation to be useless 

#### To Reproduce
1. Go to the 'Calculations' app
2. Type '√1_mm²'
3. Press EXE

#### Expected behavior
It should return the unit, with powers removed (in this instance, 1mm)

#### Environment
 - Epsilon version 13 (Omega 1.19.2)
 - Happens on the calculator (N100), and official online simulator

**Comment by RedGl0w** [comment]
This is indeed due to power that doesn't calculate any units (because they use `sqrt(x) = x^(1/2)` (https://github.com/numworks/epsilon/blob/b034f8e054f89695bb0ecd2f84c01ed66b7a8792/poincare/src/square_root.cpp#L52-L54), so they return undef for units (https://github.com/numworks/epsilon/blob/b034f8e054f89695bb0ecd2f84c01ed66b7a8792/poincare/src/square_root.cpp#L43)

**Comment by artaxxx** [comment]
Fixed in 15.0.0
