### ISSUE TITLE
How does esplion flash data onto the calculator 

### ISSUE THREAD

**Issue by raccoondude** [numworks/epsilon#1646]
I wish to add my own system, with its own kernel, onto my numworks calculator, but I can't seem to figure out how to flash the memory, can anyone show me how this is done?

**Comment by RedGl0w** [comment]
The DFU protocol (Device Firmware Update) is used on numworks to update the firmware of the device. An implementation of this protocol for host is made in build/usb/dfu.py, and for the calculator there are 2 possibilities :
- the stm32 have a default behaviour when you press 6+reset to enter in DFU
- the numworks added also in ion/src/device/shared/usb another implementation, in order to update the firmware in runtime (in order to change ram, which contains the scripts)

**Comment by RedGl0w** [comment]
Btw, this isn't a real issue, so you may close it

**Comment by Ecco** [comment]
Indeed 😄
