### ISSUE TITLE
Epsilon Numeral System Mode / Converter Hex/Dec/Oct/Bin

### ISSUE THREAD

**Issue by luoniisan** [numworks/epsilon#1656]
This calculator is really perfect for studying in "Numeric System" but it really lacks a conversion application or / and a "Bit Edit" application, that's all it lacks so that this calculator can be used on its own in my opinion, Epsilon is a programmable calculator widely used by developers, it would not be too much to add this feature

like this:
https://ibb.co/Kh33XSp
https://ibb.co/dWLxcwb

**Comment by RedGl0w** [comment]
Indeed epsilon has already a conversion system (try in calculation : `5_m->_mm` (with a real arrow)). What do you mean by bit editing? And numworks isn't a calculator made for developper (or their advertising communication is very wrong)

**Comment by adriweb** [comment]
I suppose they're talking about 1) arbitrary base (not unit?) conversions. 2) having a bit-by-bit representation of numbers where you can toggle each one, like in the screenshots.

**Comment by RedGl0w** [comment]
Arbitrary conversion is already also in firmware (base 2, 10 and 16). I didn't see the Screenshots. Thanks

**Comment by adriweb** [comment]
Well it's not arbitrary if it's limited to 2, 10, and 16 lol.

**Comment by Ecco** [comment]
I'm not 100% sure what this issue is about, but it looks a bit like #133. As you can see, we now do base 2, 10, and 16 conversions out of the box:

![Input of hex number](https://user-images.githubusercontent.com/55989/91898118-431e4580-ec69-11ea-8e2f-ec2a0cf29a74.png)
![conversion of decimal number](https://user-images.githubusercontent.com/55989/91898121-44e80900-ec69-11ea-8c30-e968545f8529.png)

If you want any other more advanced/exotic base manipulation (e.g. bit toggling, or base-37 numbers), then it's probably not something we'd be interested in merging. You definitely should be able to come up with a (short) Python script to solve those kind of problems though 😄
