### ISSUE TITLE
The graph window Y-auto size often provides non-sane values

### ISSUE THREAD

**Issue by ComradeEcho** [numworks/epsilon#1666]
#### Problem you'd like to fix
I feel like when I'm graphing functions --especially functions with vertical asymptotes-- the system often chooses absolutely insane Y-axis window sizes that are hundreds or thousands of times bigger than the X-axis. 

Perhaps there's a reason for it to function this way, but drives me nuts every time it happens and I'm always having to re-square the window.

for example if I graph (10+x)/(x-1), the graph puts me at -10 to 10 on the X axis, and -1070 to 3758 on the Y axis

Another example is x^4 gives a graph window that's -10 to 10 on the X axis and -1725 to 10757 on the Y axis

I rarely ever want to see a graph where the Y scale is 1000x larger than the X scale, and I don't think it should be default behavior.

#### Screenshots
I find these Y-auto range to be completely useless for seeing the shape of the graph
![Screen Shot 2020-09-20 at 8 00 00 PM](https://user-images.githubusercontent.com/4523694/93726525-1bd9da80-fb7c-11ea-9603-c81d58fd3320.png)

![Screen Shot 2020-09-20 at 8 15 33 PM](https://user-images.githubusercontent.com/4523694/93726989-9c99d600-fb7e-11ea-8e2f-74ccf7fa7dd7.png)

#### Describe the solution you'd like

Whenever I come across this issue, I just set the pre-adjustment to "orthonormal" and zoom zoom zoom until I can see what I want to see. 

I understand that it's probably not an easy job to mathematically determine automatic yet sane window sizes... 

Perhaps the real issue here is not just the Y-auto, but also the X window being automatically set to -10 to 10 and then adjusting Y until it "fits", even if that fit results in a non-sane 1:1000 aspect ratio

I don't have any real solution - I just know the current behavior drives me insane every single time it happens.

**Comment by Ecco** [comment]
I would agree that the first example is probably not handled very gracefully. But the second one seems pretty ideal to me, given the x range. Seriously, in that second case, what else would you want to see??

**Comment by AdieAdior** [comment]
In the second example, I think it's less about wanting to "See" more, and more about being able to trust what I see.

Every time I see that crazy Y scale, I know that I have to resize the graph manually to see what it *actually* looks like, because I can't trust the shape of what's presented by default

Sure, the graph fits fantastically in the screen, but there's no way I can trust what I see when it has a 1:1000 stretch

The graph would fit equally as well with an X range of -1 to 1, and a Y range of 0 to 1, and you can trust the shape you see there because the aspect ratio is 1:1 rather than 1:1000



That's why I wonder if part of the problem stems from the system automatically setting the X range -10 to 10 and then adjust Y until it "fits", but I understand that it's difficult to predict what the user might actually want to see.



![Screen Shot 2020-09-21 at 12 54 37 AM](https://user-images.githubusercontent.com/4523694/93736310-894e3100-fba5-11ea-925f-48ce968ee4c5.png)


Here's another example that really sums up what I wish the calculator was doing by default:

f(x) = x³, comparing Y-auto with Y = -10 to 10... 

I think the first graph is really hiding the true shape of the function and it's not a window range I would ever want to see with this particular graph

The second graph is more in line with what I would expect to see when I graph this function, and the graph is more true to form
![Screen Shot 2020-09-21 at 1 01 36 AM](https://user-images.githubusercontent.com/4523694/93736767-f1e9dd80-fba6-11ea-8c1d-42a133efebb3.png)
![Screen Shot 2020-09-21 at 1 02 00 AM](https://user-images.githubusercontent.com/4523694/93736774-f615fb00-fba6-11ea-9663-35e4c7079636.png)

Another area where this stands out is when graphing function inverses, comparing the default window to what a student would actually want to see:

![Screen Shot 2020-09-21 at 1 21 26 AM](https://user-images.githubusercontent.com/4523694/93737521-10e96f00-fba9-11ea-92a5-ba72c587afcb.png)
![Screen Shot 2020-09-21 at 1 22 17 AM](https://user-images.githubusercontent.com/4523694/93737525-12b33280-fba9-11ea-8a8e-5e5ac234c748.png)


I think when students are graphing functions, it's important for them to be able to *trust* what they see, and not have to constantly resize the window to bring the *shape* in line with expectations

**Comment by suazhero** [comment]
Already raised numerous times. See #1058

**Comment by suazhero** [comment]
I think this one can be closed since 15.3.0. Most of the graphs mentionned are now plotted correctly
