### ISSUE TITLE
(+x) relative number

### ISSUE THREAD

**Issue by DegrangeM** [numworks/epsilon#1692]
#### Problem you'd like to fix
Some of my students tried to do operation with relative numbers but the calculator refused the syntax.

For example it doesn't accept `(-5)×(+4)`. More exactly it doesn't accept any positive number between parenthesis with the + signe explicitly written.

#### Screenshots
![image](https://user-images.githubusercontent.com/53106394/97110285-ab712c80-16d8-11eb-9eec-eadb4a45f61a.png)

#### Describe the solution you'd like
Numworks should allow `(+x)` notation.

**Comment by Ecco** [comment]
That's an interesting suggestion, thanks @DegrangeM !

I think it's actually a good idea. I just gave this a try in a few calculators and many didn't handle it at all, so we may want to make sure there's no "tricky" edge case that we would need to pay attention to.

That being said, we should definitely try and add this behavior, because `(-5)*(+4)` definitely makes sense. Actually, it might even do so without the parenthesis 😄

**Comment by DegrangeM** [comment]
> Actually, it might even do so without the parenthesis 😄

Not sure if it's a good idea. Maths teacher keep remembering that parenthesis are mendatorry in this case. (but this might be a french thing, I don't know).

**Comment by XanderLeaDaren** [comment]
Still present in Beta 17.0.0 – while assigned to Version 17 milestone. Any news?

**Comment by artaxxx** [comment]
We did not included it in this version

**Comment by artaxxx** [comment]
Fixed in version 20
