### ISSUE TITLE
[Functions] Auto zoom when plotting x=2

### ISSUE THREAD

**Issue by suazhero** [numworks/epsilon#1770]
#### Describe the bug
Missing the relevant part of x=2

#### Screenshots
![image](https://user-images.githubusercontent.com/55035114/106400373-6159be80-641e-11eb-91fe-a6e69b36dd50.png)

#### To Reproduce
1. Go to the 'Functions' app
2. Type 'f(t)=[2,t]'
3. Scroll down to 'Plot Graph'

#### Expected behavior
Something like that?
![image](https://user-images.githubusercontent.com/55035114/106400426-9cf48880-641e-11eb-90f1-1da7dc32b7db.png)

#### Environment
 - Epsilon version 15.3.0
 - All platforms

**Comment by GabrielNumworks** [comment]
The strategy we use when plotting parametric curves is to display the whole curve on an orthonormal range. What amount of curve gets drawn is decided by the `Plot range` parameter.

![screenshot](https://user-images.githubusercontent.com/67377994/106440907-ae1eb300-6479-11eb-97f2-70a71c25c12e.png)

By default, the plot range is [0, 360] (with degrees selected), or [0, 2pi] (with radians selected). This is the same setting used when plotting polar functions. However, it makes way more sense when applied to polar functions (as it represents one full circle) ; for parametric functions, it feels a little arbitrary.

A few solutions we could explore:
- change our default range for parametric curves to something more adequate. This is not particularly easy, as I do not believe there can be one solution that captures the specificities of each curve.
- draw more attention to the choice of range, so that the user is more compelled to select relevant values. This is us offloading some work onto the user though, which is not particularly elegant.
- find a way to expand curves that do not feel the screen, but this will require us to either hide some parts of the curve, or to abandon the orthonormal range in some cases.

**Comment by artaxxx** [comment]
Fixed in version 20
