### ISSUE TITLE
[Functions] Missing x axis when setting Ymin to 0

### ISSUE THREAD

**Issue by suazhero** [numworks/epsilon#1771]
#### Describe the bug
x axis isn't displayed when setting Ymin to 0 in Axes params

#### Screenshots
![image](https://user-images.githubusercontent.com/55035114/106400549-56ebf480-641f-11eb-81d6-e26efa1451c2.png)

#### To Reproduce
1. Go to the 'Functions' app
2. Type 'f(t)=[2,t]'
3. Scroll down to 'Plot graph'

But also occurs with a simple y=x function

#### Expected behavior
More or less the same as when inputting Ymin=-1
![image](https://user-images.githubusercontent.com/55035114/106400570-7a16a400-641f-11eb-99c8-4b974119e31a.png)

#### Environment
 - Epsilon version 15.3.0
 - All platforms

**Comment by artaxxx** [comment]
Well this is not a bug. The window starts from the bottom of the screen, that's why you can't see the axis. The banner is drown _on_ the window to avoid rescaling. Indeed, we don't want to change the scale when the banner appears or disappears (for instance when the window is orthonormal) or when the banner displays more than one line of characters.

When you go on the tab Graph, you'll see the full window.

**Comment by suazhero** [comment]
It's not really pretty but ok i guess. We need to figure the axis is actually the bottom of the window. A line could be added to make it explicit. So that it makes clear it's in addition of the edge of the window.

**Comment by artaxxx** [comment]
There are several solutions but I can't find one really convincing:
* put the axis elsewhere than in y=0, but it would be false: the x axis must be in y=0
* add a margin at the top, bottom, left and right of the graph: but this is contrary to the settings requested by the user

That's why we decided this behavior, it was the most mathematically correct and the most respectful of the user settings
