### ISSUE TITLE
Unable to compute a definite integral

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1780]
#### Describe the bug
We get undefined result (instead of an approximation of π) when trying to integrate `4x/sqrt(1-x^4)` between 0 and 1.

#### Screenshots
![screenshot (43)](https://user-images.githubusercontent.com/55989/107286820-18fa5c00-6a2f-11eb-8819-72e2f28562cc.png)

#### To Reproduce
1. Go to the 'Calculation' app
2. Type 'int(4x/sqrt(1-x^4),x,0,1)'
4. Press OK
5. See error

#### Environment
 - Epsilon version 15
 - All platforms

**Comment by rkfritzsch** [comment]
Unfortunately, I can't add anything useful to the code, but the obvious approach would be the substitution x = sin(t), thus giving an integral without singularities within its new range, namely int(4sin(t)/sqrt(1+(sin(t))^2),x,0,π/2).
By the way, the otherwise fine HP 50g fails completely with this task, in both exact and approximate calculations. An old TI89/92, on the other hand, has no problems with this integral and finds the correct answer π easily within seconds.

**Comment by rkfritzsch** [comment]
By the way, the same is true (undefined result instead of an approximation of π) when trying to integrate the even simpler expression 2/sqrt(1-x^2) between 0 and 1.

**Comment by artaxxx** [comment]
Fixed in 19.0.0
