### ISSUE TITLE
How can I graph a circle?

### ISSUE THREAD

**Issue by gabricgallo** [numworks/epsilon#1787]
Is there a simple way to graph a circle with a formula like x^2 + y^2 + ax + by + c = 0 without using parameters?  If not, it would be a good feature to add to Epsilon.

**Comment by RedGl0w** [comment]
Indeed, what you want is to be able to graph implicit function. An issue has already been created for it a long time ago : see https://github.com/numworks/epsilon/issues/837

**Comment by gabricgallo** [comment]
Right, I want to be able to graph an implicit function. That issue is very old (2018) and I think that this is an important feature in a graphing calculator; why it's in the "Later" milestone?

**Comment by RedGl0w** [comment]
> Right, I want to be able to graph an implicit function. That issue is very old (2018) and I think that this is an important feature in a graphing calculator; why it's in the "Later" milestone?

Numworks choosed not to do it to quickly, because it raises lots of question :
- How to graph it ? I see 2 solutions : either to convert it to a parametric function (which seems pretty complicated), or to test for each pixel of the graph view if the equation matches with x and y replaced (which would be super laggy)
- How to input it : currently, the graph view is always `f(x)=` (or t or theta). The UX would be very different from what graph functions look like currently. Moreover, the `x,t,theta` key corresponds to most symbol which can be added (I only see the sum not corresponding to it), and what should it input : x or y ?
There's a lot of issues with this enhancement, which is clearly necessary (for numworks team, if they don't know, in 1ère générale  in France, we have a complete chapter on the graph equation, with circles, lines, ...).

**Comment by artaxxx** [comment]
@RedGl0w explained the essence of the problem very well. For graphing, we should parametrize the curve but we must do some simplifications before that to reduce the equation. We'll probably get interested in this issue very soon.

**Comment by gabricgallo** [comment]
> We'll probably get interested in this issue very soon.

Perfect! Thank you!

**Comment by artaxxx** [comment]
It's now in version 17
