### ISSUE TITLE
translate symbols in calculation

### ISSUE THREAD

**Issue by yeKcim** [numworks/epsilon#183]
When I select french translation I expect to see calculation symbols in french :
× instead of *
, instead of . (. and , will be annoying because of buttons)
space separator instead of ,
1.10⁹ instead of 1E9

Enhancement 
Software version : 1.1.2

**Comment by adriweb** [comment]
I'm French myself and would much rather keep the way it is now, i.e. as every other software does it, it's simply more universal.
The one I disagree the least could potentially be "× instead of *" but then again, those two chars are a bit too similar: `× x`.

"1.10⁹ instead of 1E9" is the topic of other issues already, so maybe that will evolve. (You can already to exponents manually though.)

**Comment by LeaNumworks** [comment]
Hi, thanks for the issue! However, we'd rather not have a localised mathematical display for now, so I am closing it.
