### ISSUE TITLE
Thousands Separator 

### ISSUE THREAD

**Issue by yeKcim** [numworks/epsilon#184]
in calculation answer could display thousands separator

enhancement
software : 1.1.2

**Comment by adriweb** [comment]
some sort of (very) narrow space could improve readability, although I guess on the technical side, when copying them they'd have to be discarded, so it's a bit annoying.

**Comment by RedGl0w** [comment]
Using space seems to be the only solution, because comma or used, for instance, in matrix and in function parameters. If I remember well, there isn't so many countries using this separator...

**Comment by artaxxx** [comment]
Indeed, we thought about this and the space seems to be a good solution!

**Comment by RedGl0w** [comment]
So this would be pretty simpe :
- the tokenizer of the ints should be a bit reworked (because the popDigits counts all codepoints, and we can't exclude some chars https://github.com/numworks/epsilon/blob/37f78c5d4ddb2d1511a98a4f1b1cb308cea2c3bc/poincare/src/parsing/tokenizer.cpp#L55)
- the serialize in decimal would need a bit rework too https://github.com/numworks/epsilon/blob/37f78c5d4ddb2d1511a98a4f1b1cb308cea2c3bc/poincare/src/integer.cpp#L211
I'll have a look on it :p

**Comment by artaxxx** [comment]
We are working on this and there are some important design choices to make concerning the UI (size of the space) and the conventions (what about decimals?). I put this issue in version 16 but I'm not sure it will be in this version.

**Comment by RedGl0w** [comment]
Indeed, there's a lot of choices to do with this issue. For instance, the country selection could be useful to change the symbol used for separator (but as you mentioned, what about the decimal, the based integer, etc ...)

**Comment by RedGl0w** [comment]
By the way, another symbol which could be usable, without creating issue with the syntax is underscore, which is also the separator in python

**Comment by artaxxx** [comment]
Good idea! But the space seems to be the most popular/international

**Comment by RedGl0w** [comment]
> Good idea! But the space seems to be the most popular/international

Is space really international ?
I know that in France it's generally that symbol which is used, but I most often see the coma in other country (mostly in GB and US according to [this webpage of oracle](https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html)), and sometimes point is used to (like in Italy and Spain).
The pro of the underscore would be to have a real international symbol, but a char which would depend of the localization setting could be great too (even if I think the comma can't be used :/ ).
(By the way, I just realized that the underscore is not the best symbol, because space isn't used in tokenizer, whereas the underscore is used for units, even if it shouldn't be conflicting).

**Comment by artaxxx** [comment]
Yes, here is a quote of wikipedia:

> Since 2003, the use of spaces as separators has been officially endorsed by SI/ISO 31-0 standard, as well as by the International Bureau of Weights and Measures and the International Union of Pure and Applied Chemistry (IUPAC), the American Medical Association's widely followed AMA Manual of Style, and the Metrication Board, among others.

**Comment by RedGl0w** [comment]
Oh nice
I didn't know that there was an international symbol
So the space is a good symbol, but it could be replaced in the clipboard conversion (calculation to python) to underscore

**Comment by artaxxx** [comment]
It's now in version 16
