### ISSUE TITLE
Location of relocated epsilon-bootloader not existing

### ISSUE THREAD

**Issue by Vrumfondel** [numworks/epsilon#1864]
The link to the relocated epsilon-bootloader seems to be wrong (results in 404 response).

Concerned path:

epsilon/ion/src/device/n0110/epsilon-bootloader

**Comment by M4xi1m3** [comment]
The link isn't wrong, the repo surely exists but they didn't make it public yet.

**Comment by Vrumfondel** [comment]
Well - nevertheless it's not possible to build the project .....

**Comment by RedGl0w** [comment]
> Well - nevertheless it's not possible to build the project .....

You'll still able to build kernel (but you won't be able to start it), and userland.
So you theorically still can contribute to the userland.

**Comment by carl-vbn** [comment]
So is this the end of "officially supported" hardware hacking on the new hardware revision? I still have an old version where it works fine, but it would really be a shame if they decided to prevent us from using custom software. If that's the case, it's probably for anti-cheating measures, but you can still flash and modify older software versions so I don't understand how this would help.
NumWorks, please tell me it's still possible to compile and flash the latest version from source for the new hardware revision (N110), that's what got me excited about having a NumWorks in the first place!

**Comment by squidink7** [comment]
It really is an awful shame. I understand their thinking, but locking it down to the extant that even good-willed folks like the omega team can't do their thing anymore is really sad. I hope they do reconsider and loosen up a little bit, even if it's just giving permission for the omega team to base off E16 and higher. There were so many awesome features there that would be so sad to lose!!

**Comment by carl-vbn** [comment]
I honestly feel bad for all the people who bought what they thought was an entirely hackable calculator just to see themselves locked out of their devices after one update. Same for all the contributors who might feel like their code was stolen from them, locked behind a tighter license that prevents anyone but numworks from redistributing it.

I know that NumWorks probably didn't want it to go this way, but that they were probably put under pressure because of exam eligibility requirements, but I have never been fond of this mentality where a small risk ruins something for the biggest part of users who don't have any bad intentions.

To everyone who still owns a N100, hold on to it. For the rest of us, I hope that resorting to minor hardware hacks like it is possible now will remain an option.

To all the people who developed cheating software for others to use on their exams, thank you for ruining it for everyone.

**Comment by Ecco** [comment]
> To all the people who developed cheating software for others to use on their exams, thank you for ruining it for everyone.

Note that exam rules change from one test to the other. What is perfectly acceptable - and potentially a great add-on - for a given exam might very well be a cheating software from another exam's perspective.

Anyway, to reply to the original issue: yes, we decided not to publish the bootloader's code for security reasons. It pretty much only does is a digital signature check anyway, so it's quite boring really.

**Comment by RedGl0w** [comment]
> Anyway, to reply to the original issue: yes, we decided not to publish the bootloader's code for security reasons. It pretty much only does is a digital signature check anyway, so it's quite boring really.

Quite boring maybe, but usefull when trying to test kernel contributions. For instance, I did my last 2 PR without being able to test them, and one doesn't work at all, because it requires some changes in the bootloader too. But without releasing the sources, it seems pretty complicated to find any solution. Pretty sad

**Comment by matteoturini** [comment]
> > Anyway, to reply to the original issue: yes, we decided not to publish the bootloader's code for security reasons. It pretty much only does is a digital signature check anyway, so it's quite boring really.
> 
> Quite boring maybe, but usefull when trying to test kernel contributions. For instance, I did my last 2 PR without being able to test them, and one doesn't work at all, because it requires some changes in the bootloader too. But without releasing the sources, it seems pretty complicated to find any solution. Pretty sad

I'm late, but if I were you, I would stop helping Numworks do false advertising, and stop contributing to their proprietary firmware.
