### ISSUE TITLE
No longer under Creative Commons BY-NC-SA?

### ISSUE THREAD

**Issue by mattl** [numworks/epsilon#1875]
I notice that the Creative Commons license has vanished from the project.

**Comment by adriweb** [comment]
Yes as they've mentioned in their [blog article here](https://www.numworks.com/blog/secure-software-for-exams/):

> **Software license change**. There is only one change to the new software license. We no longer allow redistribution of the NumWorks calculator software. You can always submit requests and feedback on GitHub to implement changes to the official NumWorks software.

It's now under strong copyright / All rights reserved, as the readme states.

**Comment by hobbes** [comment]
damn, and I found the project so interesting...

**Comment by Ecco** [comment]
It was a tough decision to make but this is indeed the route we had to go.

**Comment by LukasAppleFan** [comment]
May I ask you what drove this decision ?

**Comment by nfitzen** [comment]
> If you wanted to ensure that your calculators were test secure without alienating the open-source community, you could continue to release epsilon under a less restrictive license that PERMITS NON COMMERCIAL REDISTRIBUTION

@memtech3 that was exactly what [CC BY-NC-SA 4.0] did. Or did you mean something like [CC BY-NC-ND 4.0]?

> and instead of COMPLETELY LOCKING DOWN the calculator to prevent unofficial firmware from being installed, you could adapt the bootloader to allow unofficial firmware but restrict access to the testing mode LED.

That would certainly be a less egregious form of bootloader locking. You could have the hardware check for a signature purely in order to interface with the light. Ideally, because tivoization is bad, this restriction would be within ROM, though that'd require a new "freedom-respecting" model.

[CC BY-NC-SA 4.0]: https://creativecommons.org/licenses/by-nc-sa/4.0/ "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International"
[CC BY-NC-ND 4.0]: https://creativecommons.org/licenses/by-nc-nd/4.0/ "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International"

[`GPL-3.0-or-later`]: https://spdx.org/licenses/GPL-3.0-or-later.html "GNU General Public License v3.0 or later"

**Comment by matteoturini** [comment]
They didn't even need to change the license. They could have just closed the bootloader, made specifications for it, and disable LED on custom software. This is bullshit. They didn't inform me of the license change when I updated.
