### ISSUE TITLE
Please update the GitHub repository with the latest sources

### ISSUE THREAD

**Issue by M4xi1m3** [numworks/epsilon#1966]
#### Describe the bug
The GitHub repository is not up to date, mostly missing epsilon 19 and a whole device worth of HAL.

#### Screenshots
![image](https://user-images.githubusercontent.com/57234558/182038013-8a4b0fde-d3e5-4931-b778-283b854c8992.png)

#### To Reproduce
1. Go to [https://github.com/numworks/epsilon](https://github.com/numworks/epsilon)
2. Observe

#### Expected behavior
The GitHub repository should be up to date

#### Environment
 - Epsilon version: 18.2.2 7c15e2e
 - The platform(s) on which the problem happens: all

**Comment by BloomyInDev** [comment]
No idea to fix it ?
Just do this easy step
go to the folder with epsilon 19
go to cmd
type "git commit"
And type finaly "git push"
Enjoy this simple tutorial

**Comment by M4xi1m3** [comment]
Bon, courant janvier donc...?

**Comment by BloomyInDev** [comment]
Why our constructive comments are marked as disruptive content ???

**Comment by Lisra-git** [comment]
The Exam Mode mechanism seem to have been changed since v19, projects that make use of it such as bootloader based CFW require it to ensure proper security in exams.
The v19 Source code have to be released soon or at least the updated exam mode system part
Thanks for doing anything that helps here

**Comment by Lisra-git** [comment]
thanks for the push
Can we expect Epsilon-Core to go public?
Thanks

**Comment by artaxxx** [comment]
No, unfortunately we don't plan to do this. We also updated: https://www.numworks.com/resources/engineering/software/build/
I close this issue since we released the sources for version 19

**Comment by Lisra-git** [comment]
Hello @artaxxx 
I did go through all the changes of E19 and while there a lot, it seem that kernel part which include exam mode reading/writing mechanism has been hidden with it
Can it be expected to have it back?

Also is the N0100 code drop is the end of N0100 or just github repo move due to New-Ion?

Thanks for any replies

**Comment by artaxxx** [comment]
No we don't plan to release the kernel sources, especially the part related to exam security.
Concerning N0100, it's not on master anymore since the code base diverged because of memory restrictions

**Comment by Lisra-git** [comment]
Thanks @artaxxx for the replies and information about N0100 which got me worried since code release glad to hear it's not done yet!

Btw, is the new N0120 model featured in Code coming soon to store?
It's been a long time I heard about it and haven't saw one yet in store.

Thanks for any replies

**Comment by devdl11** [comment]
> No we don't plan to release the kernel sources, especially the part related to exam security. 

Thanks for your reply, but, in my opinion, the last part regarding the exam mode, that "you will not disclose the part related to exam security" doesn't make any sense to me, because this part is already accessible and is located in `poincare/src/preferences.cpp`.

What we want, is only how you store in flash the current exam mode, nothing else. However, I think we all know what's going on now...
It's not that you want to preserve some "security related to the exam mode", because you already know that we can legally reverse engineer your software,  you just want to kill all third-party software that is based on epsilon 15.5, which makes me wonder: how that comes with your "convictions"? (which, between us, it hasn't been true for a long time...). 
All we want, again, is to secure our software for the exams, and It's disappointing to see what path you have chosen to follow, a path against the community and your historical convictions. 

Thanks for reading me, I don't expect any reply, even if you will mark my comment as "disruptive content" because I go against "your convictions".
