### ISSUE TITLE
Bonjour, ce serais bien d'ajouter un mini store dans la calculatrice ou sur le site numworks pour telecharger des applivation mathématique merci !

### ISSUE THREAD

**Issue by Sajid33bled** [numworks/epsilon#1982]
#### Problem you'd like to fix
Is your feature request related to a problem? Please provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Please describe a **single** improvement per issue. Feel free to open multiple issues though!

#### Screenshots
If possible, please attach a screenshot. You can go on our [online simulator](https://www.numworks.com/simulator), use the screenshot button, and drag'n'drop the file here.

**Comment by artaxxx** [comment]
Thank you for your issue!
I take the liberty to close it because a description is missing (you left the template in the comment). I leave you free to open a new issue and I invite you to write it in English. We have indeed users from several different countries and it will help everyone to understand the subject! Thanks!
