### ISSUE TITLE
Land on the calculation app after power on

### ISSUE THREAD

**Issue by ChuckM** [numworks/epsilon#199]
I love the flexibility here but the thing is first and foremost a calculator. Ideally if you click it 'on' it should be ready to calculate. It is great that it will stay in the calculator app if you turn off and then on while you are in the calculator app, but I would really appreciate a setting that always brought it up in calculate if it wasn't in some other app before. That will probably be my first PR.

**Comment by AlainBusser** [comment]
:-1:  If it was the case nobody would guess that you had to hit the :house: button to access other apps, and the role of the navigation inside **this** calculator.

**Comment by ChuckM** [comment]
Possibly @AlainBusser, my favorite calculator is the TI-92+, it comes up in calculate and you press the 'apps' button to do other things. Similarly with the HP series, which were calculators first and then with the 'menu' key you got to other features. Having run through the code the change is fairly simple to make and you could easily A/B test it with your candidate audience. I super appreciate that the source is available so that I can change it on my own of course. 

My current plan is to get at least one more, however if I end up with 2 or three I have a number of discovery/UX questions to explore here.

**Comment by Ecco** [comment]
Hi @ChuckM ! Thanks for this suggestion. This is something we considered for a while but decided not to pursue. Our experiments with high-school students have shown that landing on the home screen instead of the calculation app seemed a lot more customary to them (that's how phones and tablets behave).

We're also trying to make the device as simple to use as possible, and one way to achieve that is to limit the number of settings, so unfortunately we probably won't add a setting for this feature. I'm closing this for now, but don't hesitate to reopen if needed.
