### ISSUE TITLE
poincare inside Python?

### ISSUE THREAD

**Issue by AlainBusser** [numworks/epsilon#201]
This is about an enhancement:

If my Python script begins with from `kandinsky import *` I can draw from within Python. Maybe one day I will be able to create widgets in Python, and have a powerful app written in Python :wink: 

But  if I try `from poincare import *` or `print(binomial(8,5))` I have an error message. I guess it is related to the fact that, in the source code, there is a _kandinsky.cpp_ and no _poincare.cpp_ inside the _python_ folder. Is it possible to have such a file and, in this way, use the advanced functions inside the python editor?

**Comment by parisseb** [comment]
It seems to be a design issue: apps are independant, while you would also like to use the calc commands inside your programs and your Python functions inside Calc. This is something you can do on calculators like the ti nspire or hp prime (with their respective programming languages).

**Comment by adriweb** [comment]
It's basically a question of implementing the bindings to Poincare, like they were done for Kandinsky.

(Note: in Nspire-Lua, there's basically `math.eval` (returns the best appropriate type) and `math.evalStr` (returns a string).
For the NumWorks, it would be good in Python to have such a simple binding too to Poincare, to the main "evaluate" entry point, input and output both being strings).

**Comment by parisseb** [comment]
I would say that calling Calc commands from Python is easier than calling Python created functions from Calc or other Apps.

**Comment by adriweb** [comment]
Yes. I think that's what we are all talking about here. Bindings of Poincare inside Python, like for Kandinsky.

(On the Nspire, there isn't any way go call lua code from TI-Basic for instance, however since Lua can monitor variable in an async/eventful way, a TI-Basic program can change a flag/sentinel variable, Lua catches that and acts accordingly. It's useful for relatively big computations that are done faster in Lua than in Basic, and end up modifying variable values used elsewhere, like in graphs/geometry)

**Comment by parisseb** [comment]
But calling a Python function from elsewhere is much more important on the Numworks than calling lua from the nspire commandline because there is already a programming language callable from the commandline on the nspire. The easy way to do that is probably to be able to replace the Calc application parse/eval by a Python kernel and that could also prepare the Calc app for interaction with giac if more flash is available in the future.

**Comment by ericflores** [comment]
> 
> 
> But calling a Python function from elsewhere is much more important on the Numworks than calling lua from the nspire commandline because there is already a programming language callable from the commandline on the nspire. The easy way to do that is probably to be able to replace the Calc application parse/eval by a Python kernel and that could also prepare the Calc app for interaction with giac if more flash is available in the future.

Looks that with the current hardware and software stack this is challenging, but I agree that this opens the door to grow the platform to new levels. If you can define a python function that could be called from the calculator as a regular function, this would be awesome. For example, if I have a Laplace Transform program defined in Python, I would like to call it from the Calculator as a function as follows:

    Lap('-2/(5*e^(2*x)) + (2*cos(x) + sin(x))/5', 'x')

and get this output as **ans** in the stack:

    w/(w^3+2*w^2+w+2

Of course, this requires a mechanism to register python scripts to thecalculator's function namespace without loading them until they are are actually used.

**Comment by boricj** [comment]
The problem with calling Python functions from Poincare is that there's no Python context to tap into. The Python app loses all its state upon exit because its context is freed. While the Python context can be made persistent across apps, this will cost a significant amount of RAM and there's not a whole lot of spare RAM to begin with...

**Comment by artaxxx** [comment]
This issue has been open for a long time and we have no plans at this time to include a Poincaré library in Python. This is why I close this one. The best way would be to handle regular Python libraries to do calculations
