### ISSUE TITLE
Using lists for inference

### ISSUE THREAD

**Issue by augsbukn** [numworks/epsilon#2158]
Modify the inference options to include an option to pull from lists for data rather than having to enter the commands for mean, stdev, sample size.  Consider TI's option within inferences to use stats (entered) or pull from data (lists).

**Comment by fbeleznay** [comment]
I also support this suggestion (from the point of view of an IB math teacher).
Apart from being more efficient, it would also reduce the problem of using the wrong standard deviation. As far as I know, students need samplestdedev(L) when they want to make an inference based on a data set and not stddev(L).
All other graphing calculators I know of (TI84, TInspire, CasioCG50, HPprime) have this option. Students using a Numworks are slightly disadvantaged on exams because of this missing option.

**Comment by adri1numworks** [comment]
Hello,
Thank you for your suggestion. We are currently developing this option. I will let you know once it is released !

**Comment by augsbukn** [comment]
[like]  Kristen Augsburger reacted to your message:
________________________________
From: adri1numworks ***@***.***>
Sent: Monday, March 11, 2024 1:26:37 PM
To: numworks/epsilon ***@***.***>
Cc: Kristen Augsburger ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [numworks/epsilon] Using lists for inference (Issue #2158)


Hello,
Thank you for your suggestion. We are currently developing this option. I will let you know once it is released !

**Comment by KarineNumWorks** [comment]
Hello ! 
This feature has been released in version 23: https://www.numworks.com/calculator/update/version-23/#:~:text=Using%20data%20in%20the%20Inference%20app. 

I will close this issue consequently ! Thank you !
