### ISSUE TITLE
UK Exam Mode is not fit for purpose

### ISSUE THREAD

**Issue by r-mills** [numworks/epsilon#2164]
Hi,

We are a large UK A Level college that has gone ‘full NumWorks’ and required all students to purchase a NumWorks calculator for their A Levels. We have around 300 students studying A Level maths in total. We are extremely enthusiastic about the improvements to teaching and learning that the NumWorks has enabled…

However, I have two concerns about the current implementation of the UK exam mode which currently mean it is, in my opinion, not fit for purpose as a way of identifying that the calculator is meeting the JCQ requirements for exams.

1) Given that the only way to be sure that a calculator is running official software in exam mode (rather than being flashed to an insecure software) is through the LED being lit in exam mode - why does this not happen in the UK exam mode? This would also make it much easier for our invigilation team to check that all calculators are set in exam mode at a glance whilst walking around the exam hall.

2) Given that there is no time-out on exam mode, it is currently possible for a calculator to be put in exam mode days or weeks before the exam and then, since Python is still active, for extensive notes to be written within the Python app for access during exams. There would be no indication to an invigilator that this has been done. For comparison, the main competitor in the UK (Casio’s CG50 calculator) does disable Python in exam mode. In the UK there is no need for Python to be active for any exam studied in any subject, so in my view it should be disabled, just as the CG50 does.

Is it possible to address these issues?

**Comment by adri1numworks** [comment]
Hello,
Thank you for your message. 

Actually, when we created UK exam mode, we made sure we answered JCQ requirements. In order to clarify this topic, could you contact us at: contact@numworks.com ? There, we will be able to discuss your issue. 

Meanwhile, here is a workaround: if you set calculators in Country = Netherlands (with Language remaining in English), you can activate the exam mode. There, an orange LED blinks and Python is forbidden. 

Hope this helps !

**Comment by jrkimber** [comment]
Hi,

I have just tried this workaround and unfortunately it is not appropriate for use in UK exams as some of the mathematical conventions, for example bases of logs, are changed. 

Is there any reason why the LED can't flash in UK exam mode but can in other countries' exam modes?

In addition, on the Casio CG50, the exam mode icon flashes rapidly for the first 15 minutes after a calculator has been put into exam mode to indicate to invigilators that the calculator has not been in exam mode for a long time and had data stored in it. Would this not also be possible with the Numworks? 

Thanks,
James

**Comment by adri1numworks** [comment]
Hello, 

Thank you for your input! The reason why we did not implement a blinking light in UK is because we understood that there is no national exam requirements, provided by the State (JCQ is only an organisation among others). For other countries, the exam mode is unique, which is why we have a LED color per country. 

We are willing to discuss further this issue in order to improve our way to answer to exam needs. Could you email us to: contact@numworks.com , in order for us to answer your needs at best ?

**Comment by r-mills** [comment]
Hi

Thanks. Although there are different examining bodies here, the JCQ is the single overarching organisation that provides the exam requirements that apply to all national exams pre-university across all of the UK, and all of the exam boards are required to follow their standards, so it is effectively the same situation as in other countries. There are no 'competitors' to the JCQ. I will send in an email with a bit more detail.

**Comment by Gemme10** [comment]
This is a very important issue for UK students and a solution in the next update would be really appreciated.

**Comment by adri1numworks** [comment]
Hello all,
After exchanging by email with @r-mills, we agreed that the UK exam mode will be updated in order to:
1. Block Python app
2. Make the LED blink (color will be blue, which is not yet used for any other country)

This should make UK exam mode safer and I understood it meets JCQ requirements. 

I will update this ticket once this update is released. It is planned for the next version.

**Comment by adri1numworks** [comment]
Hello,

A quick update on this issue : we would like to exchange with an official representative of JCQ, in order to confirm that our new features for the UK exam mode does meet their requirements. However, we were not able to reach one until now. We prefer not to update the calculator before having obtained this confirmation. 

This issue is hence "on pause". Thank you for your understanding

**Comment by Gemme10** [comment]
Although I am fairly certain you will meet JCQ criteria after implementing changes suggested by @r-mills, it would be very welcome if the manufacturer can confidently advertise the proven exam compliance of their product. 

[FAQs-–-Using-Calculators_FINAL.pdf](https://github.com/numworks/epsilon/files/14908519/FAQs-.-Using-Calculators_FINAL.pdf)

You will find contact details for JCQ on https://www.jcq.org.uk/contact/.
I understand that JCQ does not test or certify devices. Demonstration of compliance is the responsibility of the candidate (with the support of the manufacturer).

We look forward to your update.

**Comment by adri1numworks** [comment]
Hello,

In the end here what has been decided : Python app is now blocked in UK exam mode. However, we decided not to activate the LED. This is not something required in the JCQ requirements. We might do it later but for now, we estimated it is safer to proceed with this decision. 

You can find this update in the beta of our version 23 (https://www.numworks.com/calculator/update/version-23/). 

Let me know if you have any question.
