### ISSUE TITLE
Implicit degree to radian conversion in complex number polar format

### ISSUE THREAD

**Issue by achkasov** [numworks/epsilon#2171]
#### Problem you'd like to fix
There is no convenient way to convert degrees to radian when entering a complex number in polar format (see screenshot below),

#### Screenshots
![image](https://github.com/numworks/epsilon/assets/14052589/9da5c436-74c4-477e-ae85-902484050cdc)

#### Describe the solution you'd like
I would prefer the polar format complex number to implicitly convert degrees to radians when the degree unit is used.

#### Describe alternatives you've considered
A workaround is to define a constant `2 pi / 360 -> deg` and use it instead of the degree unit.
Another alternative would be the complex number angle notation which is used in HP calculators: `1∠30°`

#### Additional context
Ideally, it would be nice to recognise when the calculator is in the DEG mode and always treat the e^i as represented in degrees. To avoid confusion of the user always adding the degree unit to the calculated user input automatically, after the user presses the EXE key.

**Comment by r-mills** [comment]
I don't agree that this would make sense. e^x isn't a function in the same way that sin(x) and cos(x) are, so you shouldn't just expect for it to work for an "input" in degrees. Could you not achieve the same thing using Euler's formula if you specifically wanted to work in degrees?

![image](https://github.com/numworks/epsilon/assets/162331578/280e6cb5-52b0-496c-8513-70fefa1a7629)

**Comment by achkasov** [comment]
I agree with you here. What I expect is an automatic conversion of degrees to radians, when the calculator is in the RAD mode and the user input contains `30°`

**Comment by fbeleznay** [comment]
In high school mathematics e^(i*theta) is simply a notation for the trigonometric form of a complex number (theta being the argument). Or rather, it should be, because if we treat it as an exponential function with complex input and start using the usual properties of exponentiation, we run into trouble.
On the Numworks calculator this is the same, the form r*e^(i*theta) is called the polar form of the calculator.

In this sence, it can be confusing for students that even in degree mode the calculator interprets the argument being given in radians. 

To be fair, the manual does say that even in degree mode the polar form argument is in radians.
I can understand this from the point of view of power series, but in high school we do not work with complex power series.

Having said this, some other graphing calculators work similarly.
Even the HP prime (which the original post mentioned) considers the argument in the Euler form in radians (even in degree mode), but then it returns the argument in degrees in degree mode. All in all, this is a tricky situation.
![Screen Shot 2024-04-07 at 16 59 00](https://github.com/numworks/epsilon/assets/111730066/5fe3cdd7-4c87-4517-98a9-9b0c5d083f4a)
 

It would be nice though to indeed get an automatic conversion if the argument is explicitly given in degrees (and not getting an "undefined" answer.
![screenshot](https://github.com/numworks/epsilon/assets/111730066/b295eae8-b888-4336-bcb6-714ca9bed7ab)

**Comment by adri1numworks** [comment]
Thank you for your suggestions !

As @r-mills mentioned, it is not correct, from a pure "mathematical" point of view, to write exp(iθ) with θ in degrees. 
With this in mind, we have decided not to update our way of working for now. 

However, I precise there is another issue opened here : https://github.com/numworks/epsilon/issues/1161 , asking for phasor notation. It might be of interest to you. 

I close this issue but feel free to reopen it if needed
