### ISSUE TITLE
[Question] is there a way to make external apps with go or python ?

### ISSUE THREAD

**Issue by BlobIsBack** [numworks/epsilon#2212]
Basically make an app like you could have on other calculator or epsilon forks

For the python one i know there is already scripts but I think python external apps can be useful to include more libraries.

And if yes, how would it be possible to install it ?

btw sorry if my English is bad

**Comment by EmilieNumworks** [comment]
Hi @BlobIsBack,
As always, this is not completely infeasible but there is no easy way to do this.
Neither Python nor Go are languages made for embedded programming, so their standard compilers won't target ARM thumb assembly.

If you really want to do that, you can:
- include [Micropython](https://docs.micropython.org/en/v1.9.3/pyboard/reference/constrained.html) written in C in your external app to interpret your Python code at run time
- find a compiler for Go targeting microcontroller assembly code (ARM thumb)
- find a transpiler from Go/Python to C and use a C compiler...

All seem quite complicated.
Tutorials in [Rust](https://github.com/numworks/epsilon-sample-app-rust), [C](https://github.com/numworks/epsilon-sample-app-c) or [C++](https://github.com/numworks/epsilon-sample-app-cpp) are available otherwise.
