### ISSUE TITLE
Share same stockage for app .nwa than for python files

### ISSUE THREAD

**Issue by Idaill** [numworks/epsilon#2224]
Just this idea, i dont know if that could generate trouble but else, why not?

This let's us have more space for what we want.
Have a nice day :)

**Comment by EmilieNumworks** [comment]
Hello @Idaill! Thanks for the suggestion.
.nwa code lives in flash and has to have its own sector to be rewritable.
If we allocate .nwa RAM (stack/heap/data) at the same range as python files, the latter will be overridden when the user launches the external application. I don't think it's expected by the user.
Otherwise, the .nwa RAM is already optimized to use the app buffer, the pool of mathematic expressions ([as stated in the linker script](https://github.com/numworks/epsilon/blob/master/ion/src/device/userland/flash/userland_shared.ld))
