### ISSUE TITLE
3D graphing

### ISSUE THREAD

**Issue by vcabre5047** [numworks/epsilon#2249]
#### Problem you'd like to fix
3d Graphing is unavailable from what i can tell. This would be useful for calc 3.

#### Screenshots
<img width="318" alt="image" src="https://github.com/user-attachments/assets/fea899f8-7739-4933-9c1b-d0183280ff7a">

#### Describe the solution you'd like
I would like the option to have 3d graphs like in the old TI-NSPIRE sersies, TI-89, and CASIOs as well.

#### Describe alternatives you've considered
Is there an alternative you recommend?

**Comment by MatejTymes** [comment]
I know it's not much, but for now you can use this python script:
https://my.numworks.com/python/mty/draw_3d_graph

![image](https://github.com/user-attachments/assets/ce3d92e6-a0a4-4082-8305-c68f4ba5c379)


you enter the function in the bottom like this:
draw3dGraph(
    lambda x,y: (x*x*sin(x))+(y*y*sin(y)),
    (-6,6),(-6,6),"auto",23
)
where the first (-6,6) is the x range, then the next (-6,6) is the y range, then "auto" is the z range (in here we say that instead of saying what the range is the calculator will find out the min and max by itself), then 23 means how many lines should be between the min and max line (the more the more detailed graph, but also slower to render)

Then you can use arrows, to move the graph around or press EXE/OK to go into trace mode and move the cursor around the graph.
Also + and - is used for zoom and ( and ) for rotation.

**Comment by FaisalAhmed123** [comment]
I agree with this, unfortunately you aren't allowed imported scripts in exams, and 3D Graphs are quite useful, and currently the only feature numworks doesn't have compared to the CG-50 or other models

**Comment by adri1numworks** [comment]
3D graphing is not planned on our calculator, other than using external scripts such as the one presented by @MatejTymes (which is quite amazing by the way, thank you for your contribution!)

In addition, please remember we are not a CAS calculator and cannot be compared to TI-Nspire as such. 

I'll close this issue. Feel free to reopen it if needed

**Comment by MatejTymes** [comment]
btw. is there any chance that people could publish their scripts in an easily searchable place and maybe others could upvote and downvote the provided scripts so the best ones could be easily discoverable?
also if other people could provide some feature requests, that would be great as well.
i know that i had some difficulties finding some 3d graphing script that would have the features i wanted, but am sure others might want to improve what is already there and others didn't thought about (but would be still nice to add)?
