### ISSUE TITLE
make clean leaves some .o present

### ISSUE THREAD

**Issue by rhaamo** [numworks/epsilon#23]
After a ```make clean``` there is still some .o present, this could create build issues (I got one) :

```
$ make clean
CLEAN
$ find . -iname '*.o'
./ion/src/shared/crc32.o
./ion/src/shared/power.o
./ion/src/shared/console_stdio.o
./ion/src/shared/random.o
./ion/src/shared/dummy/fcc_id.o
./ion/src/shared/dummy/backlight.o
./ion/src/shared/dummy/battery.o
./ion/src/simulator/keyboard/fltkkbd.o
./ion/src/simulator/display/fltklcd.o
./ion/src/simulator/usb.o
./ion/src/simulator/led.o
./ion/src/simulator/init.o
./ion/src/simulator/boot/main.o
./liba/src/bridge.o
```

**Comment by jacobly0** [comment]
You actually need to do `make PLATFORM=simulator clean` for it to clean the correct files, something which should be added [here](https://www.numworks.com/resources/engineering/software/sdk/) for all of the make commands since PLATFORM needs to be set for at least clean (to pick the correct products to clean) and app_run (to choose the native gdb instead of the cross arm one).

**Comment by rhaamo** [comment]
oh right, didn't tought about that. but make all without platform could... clean all ;)
anyway, docs to be updated I guess.

**Comment by artaxxx** [comment]
Documentation is being updated
