### ISSUE TITLE
invalid characters on windows simulator

### ISSUE THREAD

**Issue by ljoets** [numworks/epsilon#240]
I compiled linux and windows simulator as explained here : https://www.numworks.com/resources/engineering/software/sdk/
No problem with linux, but the windows version displays squares on some keys.

linux : ![linux](https://user-images.githubusercontent.com/11474581/32830572-e3bed2aa-c9f5-11e7-8221-cadf7122e7b6.png)

windows : ![windows](https://user-images.githubusercontent.com/11474581/32830574-e5f5b188-c9f5-11e7-9996-9ca5173e142b.png)

**Comment by Ecco** [comment]
Thanks for the report @ljoets ! This is most likely due to a font missing some glyphs on the Windows build.

**Comment by ljoets** [comment]
And witch font can I add on my windows vm to build it correctly ?
Thanks ;-)

**Comment by adriweb** [comment]
Indeed, although it's not too bad, since the issue will disappear once https://github.com/numworks/epsilon/pull/142 is [squash-]merged :)

**Comment by ydupas** [comment]
Hi all,

A solution, is to set font "Arial Unicode MS" for Windows platform. It's because, default Windows Arial is not fully unicode...

ion/src/simulator/init.cpp
Fl::set_font(FL_SYMBOL, "Arial Unicode MS");

ion/src/simulator/keyboard/fltkkbd.cpp
m_buttons[k]->labelfont(FL_SYMBOL);

The patch:
`$ git diff -p --raw
:100644 100644 b19386ed... 00000000... M        ion/src/simulator/init.cpp
:100644 100644 050b9de9... 00000000... M        ion/src/simulator/keyboard/fltkkbd.cpp

diff --git a/ion/src/simulator/init.cpp b/ion/src/simulator/init.cpp
index b19386ed..aedab2ce 100644
--- a/ion/src/simulator/init.cpp
+++ b/ion/src/simulator/init.cpp
@@ -29,6 +29,10 @@ void init_platform() {

   Fl_Window * window = new Fl_Window(screen_width+2*margin, margin+screen_height+margin+keyboard_height+margin);

+#if defined(_WIN32) || defined(_WIN64)
+  Fl::set_font(FL_SYMBOL, "Arial Unicode MS");
+#endif
+
   KDColor * pixels = (KDColor *)malloc(Ion::Display::Width*Ion::Display::Height*sizeof(KDColor));
   sFrameBuffer = new KDFrameBuffer(pixels, KDSize(Ion::Display::Width, Ion::Display::Height));
   /*
diff --git a/ion/src/simulator/keyboard/fltkkbd.cpp b/ion/src/simulator/keyboard/fltkkbd.cpp
index 050b9de9..c7258762 100644
--- a/ion/src/simulator/keyboard/fltkkbd.cpp
+++ b/ion/src/simulator/keyboard/fltkkbd.cpp
@@ -38,6 +38,9 @@ FltkKbd::FltkKbd(int x, int y, int w, int h) : Fl_Group(x, y, w, h) {
                                  key_width,
                                  key_height,
                                  kCharForKey[k]);
+#if defined(_WIN32) || defined(_WIN64)
+       m_buttons[k]->labelfont(FL_SYMBOL);
+#endif
     if (kCharForKey[k][0] == '\0') {
       m_buttons[k]->deactivate();
     }

`

**Comment by Ecco** [comment]
Hi @ydupas ! This seems like a good fix indeed, thank you very much! Would you mind turning this patch into a PR?

**Comment by ljoets** [comment]
Oops...
I did a git pull, and compiled the new windows simulator but I have an error when running app.exe:
![capture d ecran de 2017-12-06 13-57-53](https://user-images.githubusercontent.com/11474581/33662841-ac9e5db0-da8d-11e7-9643-bc1200d120ad.png)
What's wrong ?

**Comment by ydupas** [comment]
Yes I have the same before my patch with last rev.
With rev commit cca0cad7aa1bf1feebb5ca1a1c8c726754ab5ac6 I haven't this
assert with or without my patch.


2017-12-06 13:59 GMT+01:00 Laurent Joëts <notifications@github.com>:

**Comment by ydupas** [comment]
Yes I have the same before my patch with last rev.
With rev commit cca0cad7aa1bf1feebb5ca1a1c8c726754ab5ac6 I haven't this
assert with or without my patch.

2017-12-06 13:59 GMT+01:00 Laurent Joëts <notifications@github.com>:

**Comment by ydupas** [comment]
Hi,

Somthing wrong in this commit:
https://github.com/numworks/epsilon/commit/68e237702b5209ebc43aaecc50ef0874f3d54843


git checkout fc603df886e3fca2a062e05f24f580ad4c72c3c3
make PLATFORM=simulator clean;make PLATFORM=simulator
./app.exe
(ok)

git checkout 68e237702b5209ebc43aaecc50ef0874f3d54843
make PLATFORM=simulator clean;make PLATFORM=simulator;./app.exe
(assert error)
[image: Images intégrées 1]



2017-12-06 13:59 GMT+01:00 Laurent Joëts <notifications@github.com>:
