### ISSUE TITLE
windows simulator: crash when running python

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#242]
**EDITED: updated with latest version as of 21/12/17**
![image](https://user-images.githubusercontent.com/10530980/34265868-95967ac6-e677-11e7-8f12-256f8c19a611.png)

Running with latest github version + default python program

**Comment by medjahe** [comment]
Can someone help me?
How to execute numworks in visual studio 2017?
Visual studio requests a  file but no file works and there is no project file.
Thank you for any suggestions.


Quelqu'un peut-il m'aider?
Comment executer numworks dans visual studio 2017 ?
Visual studio demande un fichier de démarrage mais aucun fichier ne semble adéquat et il n'y a pas de fichier projet.
Merci pour toute suggestion.

![image](https://user-images.githubusercontent.com/39855633/41092897-388034f6-6a4a-11e8-80d9-5d4ab3ac78fc.png)

**Comment by adriweb** [comment]
It's not made to be used within an IDE, like Visual Studio, as-is.
You can simply open a terminal/console and launch something like `make PLATFORM=simulator` to make it build. (Download mingw or similar to get the build tools)

**Comment by medjahe** [comment]
thanks for the quick and clear answer.
cordially

merci pour la réponse rapide et claire.
cordialement
--------------------------------------------
En date de : Jeu 7.6.18, Adrien Bertrand <notifications@github.com> a écrit :

 Objet: Re: [numworks/epsilon] windows simulator: crash when running python (#242)
 À: "numworks/epsilon" <epsilon@noreply.github.com>
 Cc: "medjahe" <nounouanou@yahoo.fr>, "Comment" <comment@noreply.github.com>
 Date: Jeudi 7 juin 2018, 12h27
 
 It's not made to be used
 within an IDE, like Visual Studio, as-is.
 
 You can simply open a terminal/console and launch something
 like make PLATFORM=simulator to make it build.
 (Download mingw or similar to get the build tools)
 
 —
 You are
 receiving this because you commented.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by medjahe** [comment]
Hello adriweb,
is there an application that can open the source files for executing and modifying them?
I ask this because I saw on github people propose changes and give a new interface to the program. For example :

Graphical Keyboard Overlay for Simulator and matching buttons # 142
https://github.com/numworks/epsilon/pull/142

thanks for all the help and explanation.
cordially

Bonjour adriweb,
y-a-t-il une application qui puisse ouvrire les fichiers sources afin de les éxécuter et de les modifier ?
Je demande cela car j'ai vu sur github des personnes proposer des modifications et donner une nouvelle interface au programme. Par exemple :

Graphical Keyboard Overlay for Simulator and matching buttons #142
https://github.com/numworks/epsilon/pull/142

merci pour toute l'aide et les explication.

cordialement

**Comment by adriweb** [comment]
To modify files, you can set up the project in your favorite text editor or IDE (for instance I use Clion and it works perfectly fine), just don't expect to be able to build with it if you didn't fully configure it to do so (it may be a pain depending on the target). So basically just setup the project minimally enough so that the editor/ide can inspect/analyse/understand the source code, make your changes, and build with make from a console window.

**Comment by medjahe** [comment]
thank you very much adriweb for all the explanations.
I will try to put all this into practice.
Have a good day

merci beaucoup adriweb pour toutes les explications.
Je vais tenté de mettre en pratique tout cela.
Bonne journée

**Comment by Ecco** [comment]
Given how much the simulator has changed (for instance, moving from FLTK to SDL) it's safe to assume this is no longer relevant.
