### ISSUE TITLE
IRC channel?

### ISSUE THREAD

**Issue by adriweb** [numworks/epsilon#25]
I see that [`#numworks` on FreeNode](https://webchat.freenode.net/?channels=#numworks) has been registered by @Ecco, but there are only a few of us there.
I think it should be promoted somewhere on the website and I guess on the repo's Readme file.
Would be even better if the developer team could join so that we could discuss things like github issues etc. more quickly!

**Comment by Ecco** [comment]
IRC is super convenient to have a quick and casual chat, but has the added cost of being yet another  place to monitor.

At the moment we'd like to keep as much as possible of the code-related discussion on GitHub, because it's a centralized place which is easily accessible to newcomers.

That being said, we'll try to hang out there 😄

**Comment by adriweb** [comment]
Alright, fair point :)

One request about that however: could you enable the IRC github event hook so that things happening here will be notified there?
It should be there: https://github.com/numworks/epsilon/settings/installations

**Comment by Ecco** [comment]
Sure. Here you go 😃
