### ISSUE TITLE
(3-i)^2+6i gives the wrong result

### ISSUE THREAD

**Issue by GabArt** [numworks/epsilon#310]
![image](https://user-images.githubusercontent.com/35230066/34693269-3c162c62-f4c3-11e7-9ab4-b0f320abea2a.png)

**Comment by Ecco** [comment]
Hi @GabArt ! That's a good catch indeed, thank you very much for reporting this. This problem happens because we don't simplify the expression to 8, and then rounding errors happen when computing the approximated value. By the way, one could argue that this not a "wrong" result per-se. `8` is indeed approximatively equal to `8 + 1E-16*i` 😄 

Anyway, the proper way to fix this is by having Poincaré, our math engine, expand `(3-i)^2`. And the good news is that this is already done by #300 which should be merged to master shortly.

**Comment by Ecco** [comment]
Fixed now that #300 has been merged.
