### ISSUE TITLE
[i18n] Accents in Spanish Language

### ISSUE THREAD

**Issue by agucova** [numworks/epsilon#367]
I noticed that while using the spanish language, accents are not showed:
Función --> Funcion
Regresión --> Regresion, etc.

Would it be possible to display full utf-8, perhaps?

**Comment by jacobly0** [comment]
See #33 for discussion about this.

**Comment by RubenNumworks** [comment]
Thank you for your suggestion.

UTF-8 is supported since recently and a reasonable subset of glyphs is provided.
See https://github.com/numworks/epsilon/tree/master/ion/include/ion/unicode and https://github.com/numworks/epsilon/tree/master/ion/src/shared/unicode.
Accents in Spanish have been added.
