### ISSUE TITLE
Inconsistent expression parsing

### ISSUE THREAD

**Issue by homeostasie** [numworks/epsilon#407]
On fraction, result depend on **times** sign (*like casio*) : 

* 88/2(1+2) ) = 14.66
* 88/2*(1+2) = 132

the input / mathprint is correct.

But I found this quite inconsistence.

**Comment by Ecco** [comment]
Hi @homeostasie ! That's a good catch: the way both expressions are parsed is indeed correct but inconsistent.

First of all, I'd like to say that this is not such a big deal though because the mathematical grammar itself is by design ambiguous: `88/2*(1+2)` can be understood both as `(88/2)*(1+2)` or as `88/(2*(1+2))`.

I understand your point though: it would be better if both the implicit and explicit multiplications were parsed the same way. The way to solve this would be to make [the Bison grammar](https://github.com/numworks/epsilon/blob/master/poincare/src/expression_parser.y) used in Poincaré (our math engine) unambiguous.

**Comment by matheod** [comment]
I am in favor of making a/b*c equal to (a/b)*c.

**Comment by RubenNumworks** [comment]
> On fraction, result depend on **times** sign (_like casio_) :
> 
>     * 88/2(1+2) ) = 14.66
> 
>     * 88/2*(1+2) = 132
> 
> 
> the input / mathprint is correct.
> 
> But I found this quite inconsistence.

Note that the question holds in the _linear writing format_ only and there is no point in the _natural writing format_.

We have settled on the following:
- the division and multiplication operators have the same precedence and the operations are performed from left to right
- the implicit multiplication has higher precedence.
The examples you provided follow exactly those rules. From this perspective, there is no inconsistency.

If you think that different rules should apply, please feel free to reopen the issue.
