### ISSUE TITLE
[Functions] Allow X graphing

### ISSUE THREAD

**Issue by UDXS** [numworks/epsilon#425]
One simple feature that most graphing calculators seem to miss is X graphing. Making it possible to have functions that take y as a parameter and output x can be very useful. Also allowing computation (e.g. intersection) with these would also be good.

**Comment by Ecco** [comment]
How about… just tilting your head to the right? 🤣
Jokes aside, what's would be the use case for this?

**Comment by UDXS** [comment]
Hmmm. I never thought about that. If I wear those red and blue 3D glasses and alternate eyes while rotating my head fast enough, would that work? 

But, in all seriousness, the biggest use case comes with my previously mentioned inequality graphing. In a typical high school curriculum, X graphing isn't mentioned very much but it starts becoming important when one is graphing figures with inequalities. I don't believe it would be too hard to implement this. An extra button for it and instead of asking for Y from X, you ask for X from Y. As for scaling and dynamic fit, one only has to compute the fit for the X coordinate rather than the Y coordinate like normal. 

I'm sure this is cheaper and more practical than bundling 3D glasses with every calculator...

**Comment by Ecco** [comment]
I think this could be solved by #891 😄

**Comment by LeaNumworks** [comment]
Hi, as @Ecco said, you can graph x = f(y) by using a parametric function:
x(t) = f(t)  and y(t) = t.
I will thus close the issue :)

**Comment by suazhero** [comment]
It's true that it would be more convenient to add the capability to input x=2 to draw lines instead of 
![image](https://user-images.githubusercontent.com/55035114/76093143-c879b380-5fc0-11ea-9e2a-e35284d7aba8.png)

Especially considering high school students most likely never heard about parametric representations.

Notice how the auto zoom fails in that case too. See enhancement request #1058 
![image](https://user-images.githubusercontent.com/55035114/76093445-4342ce80-5fc1-11ea-8497-ede3614848a4.png)
