### ISSUE TITLE
[Functions] Minor display glitch when waking the device up from sleep

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#500]
This is a minor and very specific bug.

Just updated with today version. Don't know if this bug also exist on older version.

1) Go on fonction and create a f(x) = sin(x) fonction.
2) Show the graphical representation of the function, then open the zoom menu
3) Turn of the numworks, then turn it on again.
4) For a small duration you should see a glitch at the bottom (where zoom key are written).

This bug also happens with cos, square and frac function, but doesn't happens with all function.
With the floor and ceil function, the glitch is only on the bottom right section, but the size of the glitch vary with zoom and position.
For square root and ln it happen if you move on the right.

This is probably related to the time required to draw the function.

**Comment by Ecco** [comment]
Indeed, thank you for reporting this @matheod !

It's been like this for a while (tested on 1.4.1, but most likely there since a lot earlier). The glitch happens because it takes a while for the curves to be drawn, and those are displayed before the zoom menu. In the meantime (until it's redrawn), there's garbage where the zoom menu will be.

The more functions you have, the slower they are to draw, and the longer the glitch. It's actually barely noticeable with just a sine function though (less than 0.1 second actually).
