### ISSUE TITLE
Plotting implicit and polar equations, argand diagram?

### ISSUE THREAD

**Issue by chocol4te** [numworks/epsilon#515]
Are these planned features?

If not, some pointers or rough outline of how I could go about implementing them would be great! :)

**Comment by boricj** [comment]
For polar equations, I would create a dedicated app modeled after `graph` rather than extending `graph`. Looking at the code, the architecture is biased towards that solution since there's a bunch of  generic classes inside `apps/shared` and the `graph` app subclasses them into cartesian implementations. A bare-bones, gutted clone of the existing `graph` app sounds like a fairly easy task to accomplish, especially since you won't have to retrofit support for multiple types of functions.

I don't think epsilon can handle implicit equations yet, I did not see a solver inside `poincare`.

For argand diagrams, one way would be to modify the `regression` app into accepting multiple data formats (vector of complex numbers, two vectors of real numbers...). However, at this point the lack of integrations between apps will severely limit your ability to provide said data. One usecase for example would be crunching numbers inside `calculation` using functions defined inside `graph` to plot the results inside `regression`, which is basically an impossible task for now.

**Comment by chocol4te** [comment]
Thank you very much for your help! :)

**Comment by RubenNumworks** [comment]
Since version 12 of Epsilon, polar and parametric curves can be plotted.

Implicit functions are already mentioned in #837.
