### ISSUE TITLE
Multiply symbol is hard to read

### ISSUE THREAD

**Issue by kauderni35** [numworks/epsilon#545]
I find the "multiply" symbol hard to read.

> Bonjour,
> je trouve le symbole "multiplier" pas vraiment visible. Est-ce que cela pourrait être changé ?
> Sebastien

**Comment by Ecco** [comment]
I assume you're talking about the `⋅` symbol used in the natural writing mode. Here's a comparison:

#### Linear writing mode
![Linear](https://user-images.githubusercontent.com/55989/41091029-eef973fa-6a45-11e8-8700-d53ebad73f93.png)
In the text field, we have a separate multiply symbol that's a lot more visible. But once the text has been parsed and printed, it becomes a small dot, which is what most people are looking for. We've even been asked to remove the "dot" altogether (for example here, we would simply print "3x" instead of "3⋅x"), but that raises other issues (how would you know if "ba" means "b*a" or the variable named "ba"?).

#### Natural writing mode
![Natura](https://user-images.githubusercontent.com/55989/41091058-fbbc6d68-6a45-11e8-917c-d20ec1066504.png)
The goal of this mode is to layout the expression as it's being typed. That's why, even during input, we're using the small dot.

**Comment by matheod** [comment]
3×2+1 look strange 3 · 2 + 1, especially for young student I think.

Maybe the × should appear when there is a multiplication between 2 numbers.

About ba meaning "ba" or "b*a", we can't have variable with multiple letter in calculus if I am not wrong. The only location where it can happen is in python but here we don't have the · symbol. Or maybe you are thinking about ln(x+1) which could means l·n·(x+1) or ln(x+1) ?

**Comment by kauderni35** [comment]
Oui, il me semble que 3x2+1 écrit comme cela serait plus lisible pour des élèves qui ont souvent peu de recul face au résultats donnés par la calculatrice...

**Comment by matheod** [comment]
It's not that bad if we limit the × to numbers multiplication : 

![image](https://user-images.githubusercontent.com/339611/41095037-8240c9b0-6a50-11e8-96fd-1222c5d38fd6.png)

An other possibility could be to add color to operator.

**Comment by TrakJohnson** [comment]
What about using a star, like the TI calculators ?

**Comment by matheod** [comment]
> What about using an asterisk-like character, like the TI calculators ?

Why not but less fan. An other posibility would be to have a curved x.

**Comment by Ecco** [comment]
We've implemented this 😄 We've settled on a mix of `×` and `•`, depending on the context.

**Comment by Ryder17z** [comment]
> We've implemented this 😄 We've settled on a mix of `×` and `•`, depending on the context.

sounds weird. would it be possible to add the option to replace both with an asterisk ?

**Comment by Ecco** [comment]
> sounds weird

I suggest you give it a shot and file a new issue if you don't like a specific behavior 😄

**Comment by Ryder17z** [comment]
> I suggest you give it a shot and file a new issue if you don't like a specific behavior 😄

I'm still undecided as I want to see the thing irl first.
