### ISSUE TITLE
Restart System on Large Settings Change (eg. language)

### ISSUE THREAD

**Issue by UDXS** [numworks/epsilon#550]
While I was trying to fix the issue where the Math Toolbox wouldn't change language, I discovered that it wasn't changing because the Math Toolbox was global, unlike the Python one. This meant that it wouldn't be reinitialized on language change/app opening. I propose we restart the system when language/other important preferences are changed. We don't have to do a full restart however. A good example for this is iOS, which displays a black screen with the words "Changing language..." while it is reloading everything. Doing this would make the system more stable overall.

**Comment by Ecco** [comment]
> A good example for this is iOS, which displays a black screen with the words "Changing language..."

I believe that's not a great UX. iOS probably has tons of things to change following a locale change (e.g. only allowing some WiFi frequencies), so that might be the only solution that can work there.

On our device, there aren't that many things to take care of. In terms of UX I think it'd be better to just reload what need be (which could/should be pretty much instant). Not that rebooting takes a long time either, but I doubt you'll want to erase pretty much all your data following a language change.
