### ISSUE TITLE
Battery icon issue

### ISSUE THREAD

**Issue by ghost** [numworks/epsilon#633]
The battery icon would jump to 50% then go back to 100% then go back to 50% and so on. When the screen is dimmed the battery icon stays at 100%.

**Comment by boricj** [comment]
It's probably because your battery is currently hovering just around 3.8v, which is the cut-off voltage between fully-charged and charged in-between states. It's flip-flopping because there's no hysteresis between levels and battery voltage will fluctuate depending on power consumption. Nothing to be concerned about, but the `Ion::Battery::level` function could be improved to prevent this from happening.

Relevant source code: https://github.com/numworks/epsilon/blob/master/ion/src/device/battery.cpp#L20

**Comment by RubenNumworks** [comment]
Done in 973c2149d42ba89f5845d4c3196d8c8fb22275b2
