### ISSUE TITLE
Displayed content larger than screen

### ISSUE THREAD

**Issue by olaure01** [numworks/epsilon#649]
If displayed line is larger than screen, there is no mention that some part of the text is hidden.

![numworks_large_screen](https://user-images.githubusercontent.com/30601497/45469692-d8e20280-b72a-11e8-9f3f-dc14b1c6254c.png)

In this example, the exponent does not appear and leads to an a priori strange result. One can see the rest of the text by using the arrow keys but it requires to guess that there is something more.

![numworks_large_screen2](https://user-images.githubusercontent.com/30601497/45469802-59086800-b72b-11e8-9fda-56cccb9ef669.png)

Could it be possible in such a situation to add a specific symbol on the end of the line (resp. beginning or both) when some additional text is hidden and can be reached by using arrow keys?

**Comment by matheod** [comment]
I remember an issue talking about adding an arrow icon when text truncated but can't find it :/

**Comment by tarapitha** [comment]
I concur. My example:
![screenshot](https://user-images.githubusercontent.com/8431237/45926158-31ce4980-bf28-11e8-98c1-258d6fa147c8.png)
The formula sqrt(2x-1)-1 was used back in the days, when calculators did not have the logarithm function, but already had square root, because the function closely follows natural logarithm in small region near the 10^-3. So the answer is not actually '1'. One has to scroll all the answers that end near the right edge of the screen to be certain of not missing part of the answer.

**Comment by Ecco** [comment]
Fixed by #903 😄

**Comment by olaure01** [comment]
I do not see the modification. I get the very same screenshot on the current version of the emulator and on the (just updated) physical numworks:
![screenshot](https://user-images.githubusercontent.com/30601497/55643647-ff08e600-57d3-11e9-9401-b8dc2c2e792b.png)
Is it for a future version only?

**Comment by Ecco** [comment]
The code has been written and merged into the master branch, but it hasn't been deployed to a public version just yet. Hopefully it'll be part of version 11 😄
