### ISSUE TITLE
issue with the zoom function

### ISSUE THREAD

**Issue by erwanh1** [numworks/epsilon#694]
I've tried to graph the function define by f(x)=1/(1-x)-2/(1-x^2) and zoomed around the the x=1 zone.
This is what I get with the emulator or the calculator.
![screenshot 1](https://user-images.githubusercontent.com/33050855/46255053-ddcbe380-c498-11e8-9360-963dfaac68f9.png)
It seems a bit weird.

**Comment by tarapitha** [comment]
I do not think that this is fault in Poincare. The Desmos online grsaphing engine gives the same weird graph around x=1 : https://www.desmos.com/calculator/vrbsoip4ou
Maybe it can be explained by noting that the function is not defined at x=1, and the calculation engine loses accuracy near this value because it consists of subtracting one big number from another. So the 'undefinedness' grows on the way to x=1.

**Comment by erwanh1** [comment]
Indeed, such weird things also appear with geogebra ,HP Prime and Casio graph 75/90.
However, with the Numworks, it seems to appear very quickly. With other softwares/calculators, I need to zoom a lot to get the strange plot.

**Comment by madhatter0** [comment]
I can confirm it's the same on a TI-84+, also.  I can also confirm the point about zooming; I see the behaviour around x=0.995 on the Numworks, whereas I have to go to x=0.99995 in the TI to see it.

It's not an issue for me, I just have my (old, dusty, not used any more because I like my Numworks) TI to hand, and thought I'd add some data in case it was useful.

**Comment by Ecco** [comment]
The issue most likely arises faster due to the fact that we do single-precision computations to make graphs snappier.

I think that'd be one of the cases where simplifying the expression before plotting it could prove useful. (Unless I'm mistaken the input is equal to -1/(x+1) unless x=1)
