### ISSUE TITLE
Adding a language

### ISSUE THREAD

**Issue by Quent-in** [numworks/epsilon#71]
Hello,
as explained to Romain I would like to add the Occitan language (Talked in Spain, Monaco, Italy and South France).
I wonder how to do:
on the file, should I add it after Portuguese or before?
I'd like to start translating this week-end.

**Comment by Quent-in** [comment]
Any news @artaxxx so we can start?

**Comment by artaxxx** [comment]
For now, it's not that easy to add languages @Quent-in. Actually we want to allow the user to select his own features and languages when he updates his calculator. You can read the comments on issues #33 and #84. We have to find a way to add multiple languages in the code without embedding all of them in the device.

**Comment by boricj** [comment]
There is also the need for decentralizing the translations for out-of-tree third-party apps., which is something that #73 does (crudely). However, it does not _untangle_ the translations from each other.

**Comment by Quent-in** [comment]
Why wouldn't you embed all the languages available? It's just some kb per language.
@boricj is right! That's an impressive PR you made!

**Comment by adriweb** [comment]
Well, because when it's properly split ("untangled"), it's much easier to manage and embed on-the-fly, and a free space gain since users will mostly need 1 language anyway :)

**Comment by Quent-in** [comment]
I agree, but all the languages have to be availables by default.
And of course, having a file per language, is the best way to internationalize this product :)

**Comment by adriweb** [comment]
Heh I don't agree, I guess English+French as languages available by default would be a good start. _However_, on the first startup, there could be some special splash screen, written in many languages, saying that the user can download an (updated) OS with his language.

**Comment by Ecco** [comment]
This is fixed by #174

**Comment by JeanGauthier** [comment]
Hello @Ecco could you provide the list of files that have to be translated and changed to add a new language?
Best regards
Jean-Gauthier from Tolosa for the Occitan language

**Comment by debrouxl** [comment]
You need to modify apps/Makefile, apps/*/Makefile, apps/*.i18n and apps/*/*.i18n . See the recent commit which eased the creation of new translations and the selection of translations at compile time:
https://github.com/numworks/epsilon/commit/e6ed6c74a4765e65eb7ad54ca87f410eea6acfef

**Comment by JeanGauthier** [comment]
Alright, if we can translate this next week, will it be merged?
Or do we need to wait for something?

**Comment by JeanGauthier** [comment]
I'm thinking about the possibility to put letter such as È É Ò etc

**Comment by Ecco** [comment]
You should be able to start working on that translation today :-) Regarding letters such as É È etc, you can include them in your translation files already (UTF-8 encoded). Those won't appear in the final build just yet because there's currently no support for accented characters. But when they will, at least your files will be ready :-)

**Comment by JeanGauthier** [comment]
Do you mean a word like "sequéncia" will be changed to "sequencia" automatically?

**Comment by Ecco** [comment]
Yes. Just write "sequéncia" in the .i18n file, and for now it'll display as "sequencia". And if/when Epsilon supports an extended charset (e.g. accented characters), you won't need to modify your .i18n :-)

**Comment by JeanGauthier** [comment]
Here's my PR: https://github.com/numworks/epsilon/pull/190
Many thanks for your help @Ecco !

**Comment by LeaNumworks** [comment]
Hi all, I am closing this issue since this was solved.

**Comment by ensag-dev** [comment]
Hello @LeaNumworks !
How is this solved? Is Occitan now included in the official software?

**Comment by LeaNumworks** [comment]
Hi @ensag-dev,

So I had read quite quickly and understood the issue was about how to translate a language, and @debrouxl gave a good answer about that:
> You need to modify apps/Makefile, apps/*/Makefile, apps/*.i18n and apps/*/*.i18n . See the recent commit which eased the creation of new translations and the selection of translations at compile time:
> [e6ed6c7](https://github.com/numworks/epsilon/commit/e6ed6c74a4765e65eb7ad54ca87f410eea6acfef)

About the Occitan specifically, PR #190 did provide a translation, but we won't be merging it as it requires maintenance on our part and there is not enough demand yet. You can still get the code from this PR and compile it to make your own OS, but if you want the latest epsilon version you will have some additional translating to do, as the PR is two years old.

> _However_, on the first startup, there could be some special splash screen, written in many languages, saying that the user can download an (updated) OS with his language.

About building a custom OS to have the languages you want, the issue #84 also talks about that.

So I feel the issue can remain closed :)
