### ISSUE TITLE
[Suggestion] Dark apparence

### ISSUE THREAD

**Issue by LeSeulArtichaut** [numworks/epsilon#729]
I am a great fan of dark themes in general. As a development amateur, I always turn my text editors and IDEs into dark. I think adding a new setting, allowing to swap between light and dark themes would be so much useful and respectful for our poor eyes, especially at night.
I've tried to do it myself on a custom SDK build, and for new, I've found the color values for python editor and syntax highlighting, changed them (and of course uploaded that on my calculator).I was mostly inspired by the "_One Dark_" theme from Atom.
I wanted to use it for all the system, but I encountered difficulties finding where there were basically color values, and where I could override methods to fill everything in grey.
I would really appreciate to see someday a dark theme on the Numworks, I hope next month for the 1.9 version; or, if somebody's patient enough to give me some indications about how views and colors are handled, I could continue doing it myself.

**Comment by A2drien** [comment]
Would it be possible to reopen this issue ?
Not necessarily by an option in the settings, but at least one choice during installation / update...

**Comment by Ecco** [comment]
Well, to be honest, very few people have asked for this. I think our efforts are better invested on different areas at the moment, so maybe it's best to keep this issue closed for now.

That being said, I have to admit that I quite don't get the whole thing. If the screen is too bright, then how about just dimming it? That'll save the battery 😄

**Comment by A2drien** [comment]
The advantage of dark mode is that it does not burn our eyes. I'm sure when you code, you prefer a black background than a white background, right ? :stuck_out_tongue:
But I can understand that you have other priorities (I'm not even sure I can influence you anyway). :joy:

**Comment by RedGl0w** [comment]
> That being said, I have to admit that I quite don't get the whole thing. If the screen is too bright, then how about just dimming it? That'll save the battery smile

You said [here](https://github.com/numworks/epsilon/pull/69#issuecomment-357891283) that a theme engine could be cool in epsilon (and I'm currently working on it). The issue is that's complicated to distribute themes, because people will have to compile themselves (and for many people, that's complicated). So if you want to add a theme engine, would you have some officials theme that would be distributed with official releases, or one official theme distributed with officials release, or no theme engine ?

**Comment by PeterAlfonsLoch** [comment]
Dark Theme may not be requested a lot on Git, but surely it would be used much. Especially for students who have to use it in low light conditions. (in dorms or even when studying at home when others may not be disturbed by light) Also it lowers eye strain when using for a long time. And I have seen quit a lot of people asking for it, and even some bigger forked projects have implemented it. looking at their community surrounding the forks it seems to be one of the main reasons o use a different OS. Now with version 16, which sadly looks down a bit too much for my taste, these forks remain stuck at version 15. Maybe demand will grow then or their OS will become completely detached from the main OS.

It is never a bad idea to get in touch with such communities to improve on one own's project. Open Source is very important especially in education. It is the main reason I bought one. And only because of the lack of a dark-theme I am unsure if I should update to Version 16 or move to one of the other OS's. I'd like to remain with the creator's OS usually. And I am seemingly not the only one.

**Comment by Stephan-P** [comment]
You'll not find me asking for a dark theme, but I notice that possibly a quarter of my students have set their HP Prime in a - imo hard to read - dark mode.
So I'd say there's definately an interest within the target audience.
