### ISSUE TITLE
Print function splits long strings into lines incorrectly in the Python shell

### ISSUE THREAD

**Issue by jlachniet** [numworks/epsilon#806]
Within the Python script editor, the print function will split long strings into multiple lines, but it will do so far after the strings start to go off screen. It feels like the long strings should either be split as soon as it goes off screen, or not at all.

**Comment by boricj** [comment]
Splitting the strings as soon as they overflow the screen would result in numerous line breaks at less than 30 characters per line. Unbounded line lengths would be extremely unwieldy to scroll through and a limit will still exist because memory is not in infinite supply. As a compromise, the Python console will split lines around the 100 characters mark.

**Comment by Ecco** [comment]
That is indeed a design choice ; maybe not the best one though. You can experiment with different values by changing [this line](https://github.com/numworks/epsilon/blob/0f061d4da9551376c8cbf00a791214e66bae61a8/apps/code/console_controller.h#L81).

**Comment by jneb** [comment]
The choice of 100 is quite strange: it is very messy to scroll that far too the right, and PEP8 recommends 78 anyway.

**Comment by Ecco** [comment]
Isn't PEP8 about code formatting? AFAIK this issue is about the console when the script is running, not when you're editing code 😄
