### ISSUE TITLE
Plot implicit functions

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#837]
I'm wondering, is there anyway that the functions app could be set to accommodate functions that are equal to zero. It would enable circles, and more importantly the batman equation, to be graphed.

**Comment by Ecco** [comment]
Wouldn't this be solved by #891 ?

**Comment by boricj** [comment]
I believe this issue is about plotting equations that aren't functions in general. Parametric equations can't directly handle something like `x²+y²=1` (it has to be transformed into `x=sin(t); y=cos(t)` first) and can't handle at all something like`|x|=|y|`. I'm not sure what's the right terminology though.

**Comment by Ecco** [comment]
I think you meant implicit plots then? Chancing the title 😄

**Comment by artaxxx** [comment]
In version 17 a lot of expressions can now be plotted
