### ISSUE TITLE
Other ways of interfacing through USB?

### ISSUE THREAD

**Issue by bremenpl** [numworks/epsilon#842]
Hello there,
The whole web environment for accessing the device through USB is very user friendly and all, but it requires you to:

1. Install chrome just for this end,
2. Have internet access,
3. Rely on your website to always exist.

I was wondering, is there any more generic (developer) way of uploading python scripts to the device? Is there any native application written for any of the popular host PC OS'es? Maybe there is an API for this and one could write something simple? I would appreciate all help.

**Comment by adriweb** [comment]
It uses the standard DFU protocol, so you can use dfu-util for instance :)
Look at the dfu rule in the makefile for something that’s ready to use (IIRC)

**Comment by bremenpl** [comment]
Hi Adrien,
Thats great, thanks for info.

**Comment by Ecco** [comment]
We definitely could create a command-line tool to exchange data with a NumWorks calculator without using web technologies. Actually *anyone* could since we're using open standards and since our implementation is public 😄. That being said, I'm going to close this issue for two reasons

1. This tool wouldn't have anything to do with Epsilon *per se*, so it quite doesn't deserve an entry in Epsilon's bug tracker
2. Developing such a tool is not on our short-term roadmap.

Thanks a lot for your comments though!
