### ISSUE TITLE
Popup when low battery

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#882]
When we switch on the calculator and it have low battery, a message should tell the user that it should charge it. I have multiple student who forgot to charge their calculator and they found their calculator dead during an evaluation. Worse, the calculator show nothing when they try to charge it and they think it's broken (i assume the calculator need a minimum charge to work even when pluged in).

**Comment by boricj** [comment]
If the battery is dead then the microcontroller will be left unpowered. Plugging in the calculator in this state will trigger ST's recovery mode as a side-effect, which unfortunately leaves the screen pitch black. Along with the pop-up message, adjusting the PCB in a future revision so that ST's recovery is only triggered when *both* the reset button is hit and the calculator is plugged in as well as resetting out of ST's recovery when the calculator is plugged out would also be a nice touch.

**Comment by ptitjoz** [comment]
si je comprends bien, si la batterie est complétement vide , on ne peut plus rallumer la calculatrice ? elle est donc hs ?

**Comment by Lesquivemeau** [comment]
Non, la batterie a plat, le microcontrôleur se met en mode recovery (comme
quand reset est pressé quand la calculatrice est branchée, pour flash l'os)
Donc l'os ne boot pas et on à pa d'indication si oui ou non la calculatrice
charge, c'est contre-intuitif.

**Comment by Ecco** [comment]
Hi everyone! Thanks for chiming in 😄 I took the liberty of translating some comments into english (I left the original version below). Anyway, here's our take on this issue:
1. There is already a low-battery popup. See https://github.com/numworks/epsilon/blob/master/apps/empty_battery_window.cpp for the relevant code.
2. To go into recovery mode, you need to have fully depleted the battery. The should happen very rarely because the leakage current is very low, so one would need to use the calculator up to the popup, not charge it, and let it sit for a rather long while.
3. Exiting from said mode is not very complicated and is the first item on our [FAQ](https://www.numworks.com/resources/faq/)
4. That being said, it's true that it's not very obvious so we'll update the PCB to change this behavior. (e.g. rescue mode is triggered upon reset if, and only if, a given key is pressed).

Anyway, I'm closing this issue because, well, there's already a popup :)
