### ISSUE TITLE
strange result

### ISSUE THREAD

**Issue by AlainBusser** [numworks/epsilon#883]
![screenshot](https://user-images.githubusercontent.com/3930757/51997278-dad91200-24cf-11e9-9f41-250e5a43c92f.png)
Remark : It is the only bug which I had found at infinity. Other results are quite coherent :clinking_glasses:

**Comment by boricj** [comment]
Unless you've defined the `exp` function, I think this is the proper way to input this expression:
![image](https://user-images.githubusercontent.com/9872969/52014143-116a5900-24df-11e9-9fe0-f48ae1d72d91.png)
I'm not quite sure how poincare ends up with that result, but here it really should answer `undef`. It's not a CAS, it cannot comprehend proper limit calculus in its current implementation.

**Comment by EmilieNumworks** [comment]
Very good catch! Indeed, the issue came from the rule 0*x --> 0 which was applied despite x being potentially infinite. Step by step, the expression was reduced this way:
e^(inf)/inf --> e^(inf)*(inf^(-1)) --> e^(inf)*0 --> 0
This is fixed with #884 along with other improvements on reductions involving infinity. Thank you for catching it!
