### ISSUE TITLE
Support tactile input

### ISSUE THREAD

**Issue by boricj** [numworks/epsilon#928]
#### Describe the bug
On SDL targets capable of tactile inputs (Android, iOS...) the screen doesn't react to tactile inputs (tapping buttons, scrolling menus...). The user is forced to use the virtual keyboard to interact with the calculator.

#### Expected behavior
Tactile inputs should work on platforms supporting it.

#### Environment
Tested on epsilon version 10.0.0, Android platform.

**Comment by adriweb** [comment]
It... kind of reacts already but in a weird way (I haven't looked at the code at all yet), at least I haven't yet seen a consistent behaviour between my gestures and what happens.

**Comment by Ecco** [comment]
I'm not quite sure what the problem is 😄 On iOS and Android, this is a simulator of the original device, which doesn't have a touch screen. So touching the screen is not supposed to do anything.

At the moment, we always assume a touch/click event was meant to do something (i.e. press a key), so  we simply figure out the nearest key and press it accordingly.

**Comment by boricj** [comment]
Just because this is based on a physical NumWorks calculator doesn't mean it has to share its limitations. I get why the FTLK-based target must be as closely aligned to the device as possible because it's a developer's tool, but in my opinion the targets meant for public consumption should strive to provide the best calculator environment and UX possible.

The NumWorks team prides itself on the power, ease of use and good UX of their calculator, why should the other targets be any different?

**Comment by adriweb** [comment]
I do agree but I guess this would be quite a big development task haha
Good for the next big version? :p

**Comment by Ecco** [comment]
> The NumWorks team prides itself on the power, ease of use and good UX of their calculator, why should the other targets be any different?

Because want them to be simulators of the actual device 😄All the alternative targets (iOS, Android, Windows, Mac, Linux, JavaScript) are meant to allow users to do *as if* they had the *actual device* between their hands.

We're open to improving each target to take advantage of the platform it's running on (e.g. take native keyboard input or allow taking a screenshot), but only as long as it doesn't give a wrong impression of the original device and doesn't deceive potential future users.

Adding touchscreen support doesn't seem to fit well in that scenario, so at the moment that's not something we're interested in merging 😄
