### ISSUE TITLE
Copying code in python editor

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#938]
#### Problem you'd like to fix
Currently we can't copy (or cut) and paste lines of code elsewhere in the editor.

#### Describe the solution you'd like
Pressing either the copy or cut key enters a 'highlighter mode' where moving the cursor highlights text (no surprises there) pressing `EXE` will the add it to the clipboard, and in the case of cut delete it. This copied text can then be pasted elsewhere in the file.

#### Additional context
The main issue with this is whether the calculator can keep code in memory (with long segments this could be an issue) so maybe having a clipboard per file could work? (stores the clipboard value in the file)

**Comment by boricj** [comment]
Entering selection mode upon pressing the cut/copy button doesn't fit with how these buttons are used in other apps. Instead, we should take inspiration from computers and enter selection mode when pressing Shift+Arrow.

**Comment by INailedIt** [comment]
That's a better method actually. (I didn't know that shortcut existed)

**Comment by matheod** [comment]
> Entering selection mode upon pressing the cut/copy button doesn't fit with how these buttons are used in other apps. Instead, we should take inspiration from computers and enter selection mode when pressing Shift+Arrow.

But is this a better solution ? I think @INailedIt solution is better because it doesn't need to know the shift arrow shortcut.

**Comment by boricj** [comment]
What about erasing a selection without overwriting the clipboard? Or replacing a selection with the contents of the clipboard? Holding Shift+Arrow for selection is a well-established keyboard operation in text editors and we already have "hidden" shortcuts (left or right while in shift mode inside text widgets).

I'd change the behavior of the keypad as follows:
* Pressing *and then* releasing the shift and alpha keys toggles the relevant modes (currently it happens when simply pressing the keys).
* Pressing left or right while in shift mode triggers ShiftLeft or ShiftRight events scrolls at the start/end of the line and exits shift mode (as before).
* Pressing up or down while in shift mode triggers ShiftUp or ShiftDown events and scrolls a page up/down and exits shift mode.
* Holding shift then pressing an arrow key triggers SelectUp/SelectDown/SelectLeft/SelectRight events, inhibits toggling shift mode and selects text accordingly.

**Comment by INailedIt** [comment]
The only issue I can see with that is whether the calculator registers a continuous press instead of reading a single key pressed every tick.

**Comment by mobluse** [comment]
I noticed that Shift+Left and Shift+Right now works as Home and End, respectively. Alpha+Arrow Keys are unused. People who have used Notepad and similar editors expect that Shift+Arrow Keys mark text. Alpha+Left, Alpha+Right, Alpha+Up, Alpha+Down could be Home, End, PgUp, PgDn, respectively. ALPHA+Left, ALPHA+Right could correspond to Ctrl+Home, Ctrl+End, respectively, in normal text editors. If you hold down Shift it would work as setting shift for the next key, but if you release Shift after holding it down during a keypress the Shift status would go away. I.e. Shift would work as a sticky Shift if you press and release, without pressing other keys, but as an ordinary Shift if you hold it down during other keypresses. I think this would work as most people expect it to work.

Also, Paste is global now and I think it should continue to work that way. I.e. what you Cut or Copy from the Python Editor could be Pasted in e.g. Python Shell or Calculation, and vice versa.

**Comment by RedGl0w** [comment]
This issue can be closed since https://github.com/numworks/epsilon/commit/5de65e0d7e1282e354129d6c57478d1dfffde2d2

**Comment by LeaNumworks** [comment]
As @RedGl0w said, we implemented the copy-paste, so I am closing the issue!
