### ISSUE TITLE
Hide Python files instead of deleting them

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#945]
#### Problem you'd like to fix
All Python files are deleted when exam mode is activated. 

#### Describe the solution you'd like
The Python files could be hidden/ inaccessible (grayed out?) during exam mode and then re-shown after exam mode is deactivated.

**Comment by boricj** [comment]
Currently, the exam mode works by resetting all apps. This would require dedicated `enterExamMode()`/`exitExamMode()` methods to app snapshots which by default reset the app on entering exam mode and adding another "importation" status to scripts. Overall it should be a fairly easy task as long as the implementation is watertight.

I'd prefer the Python scripts to be grayed out or have a lock icon instead of being hidden, otherwise students with a full storage will be out of luck. Locked-out Python scripts must be deletable.

**Comment by INailedIt** [comment]
It'd also be useful for a window to come up explicitly stating that the script is inaccessible due to exam mode being on. Some examiners can be rather distrusting in the UK.

**Comment by 0b101** [comment]
Should the script names also be hidden? Someone could name their script as (equation).py.

**Comment by creikey** [comment]
I feel as if since the scripts are backed up online that it doesn't matter when they're deleted on the calculator

**Comment by boricj** [comment]
@creikey That works only if you don't forget to back up the scripts before having to enable exam mode.

**Comment by citorva** [comment]
This feature requires that the exam mod cannot be disabled during the exam. Currently, you easily can disable the exam mode using the reset key. Implementing the feature imply that the exam mode became strong.

**Comment by boricj** [comment]
Resetting the calculator resets all scripts to the default pre-loaded ones, which is harmless on a stock firmware (and a custom firmware can easily circumvent exam mode anyways). Also, implying that exam mode implementations across calculator manufacturers are "secure" is like implying that diaries with an integrated lock are "secure".

**Comment by Lesquivemeau** [comment]
Good idea, but what if the memory is full and you need to type a new script during the exam ? We should have a popup permitting to delete the hidden scripts when in exam mode.
